rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - modules/75-ce/*
        - modules/75-cf/*
        - modules/75-ci/*
        - modules/85-cv/*
        - '@ce/*'
        - '@cf/*'
        - '@ci/*'
        - '@cv/*'
      paths:
        - lodash
