/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly boldLabel: string
  readonly duration: string
  readonly checkbox: string
  readonly accordion: string
  readonly stepPanel: string
  readonly formGroup: string
  readonly sm: string
  readonly md: string
  readonly lg: string
  readonly kvpairLg: string
  readonly alignStart: string
  readonly code: string
  readonly divider: string
  readonly noLookDivider: string
  readonly stepSubSectionHeading: string
  readonly fieldsSection: string
  readonly fieldsGroup: string
  readonly withoutSpacing: string
  readonly withoutAligning: string
  readonly optionalConfiguration: string
  readonly textWithTooltip: string
  readonly removeBpLabelMargin: string
  readonly removeBpPopoverWrapperTopMargin: string
  readonly bottomSpacing: string
  readonly topSpacingLarge: string
  readonly topMargin4: string
  readonly topMargin5: string
  readonly bottomMargin1: string
  readonly bottomMargin2: string
  readonly bottomMargin3: string
  readonly bottomMargin4: string
  readonly bottomMargin5: string
  readonly topPadding3: string
  readonly topPadding7: string
  readonly bottomPadding3: string
  readonly label: string
  readonly mainLabel: string
  readonly inpLabel: string
  readonly addSharedPathsBtn: string
  readonly nameIdLabel: string
}
export default styles
