/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly optionsViewContainer: string
  readonly halfWidth: string
  readonly manifestStore: string
  readonly formContainerStepOne: string
  readonly manifestDetailsForm: string
  readonly connectorContainer: string
  readonly bp3PopoverTarget: string
  readonly configureOptions: string
  readonly addNewManifest: string
  readonly accountUrl: string
  readonly reponameField: string
  readonly repoName: string
  readonly repoNameUrl: string
  readonly saveBtn: string
  readonly drag: string
  readonly dragging: string
  readonly dragOver: string
  readonly formContainer: string
  readonly runtimeInput: string
  readonly fileHelpText: string
  readonly addFileButton: string
  readonly headerContainer: string
  readonly squareCardContainer: string
  readonly squareCard: string
  readonly sqaureCardTitle: string
  readonly disabled: string
  readonly manifestIcon: string
  readonly advancedStepOpen: string
  readonly runtimeInput: string
  readonly checkbox: string
  readonly tooltip: string
  readonly tooltipContent: string
  readonly alignSelf: string
  readonly addmarginTop: string
  readonly tooltipCls: string
  readonly helmToolTip: string
  readonly folderRunTimeInput: string
}
export default styles
