export const PipelineResponse = {
  status: 'SUCCESS',
  data: {
    ngPipeline: {},
    executionsPlaceHolder: [],
    yamlPipeline:
      'pipeline:\n  name: editPipeline\n  identifier: editPipeline\n  description: ""\n  stages:\n    - parallel:\n        - stage:\n            name: asd\n            identifier: asd\n            description: ""\n            type: Deployment\n            spec:\n              service:\n                identifier: asd\n                name: asd\n                description: ""\n                serviceDefinition:\n                  type: Kubernetes\n                  spec:\n                    artifacts:\n                      sidecars: []\n                      primary:\n                        type: Dockerhub\n                        spec:\n                          connectorRef: org.docker\n                          imagePath: asd\n                    manifests: []\n                    artifactOverrideSets: []\n                    manifestOverrideSets: []\n              execution:\n                steps:\n                  - step:\n                      name: Rollout Deployment\n                      identifier: rolloutDeployment\n                      type: K8sRollingDeploy\n                      spec:\n                        timeout: 10m\n                        skipDryRun: false\n                rollbackSteps:\n                  - step:\n                      name: Rollback Rollout Deployment\n                      identifier: rollbackRolloutDeployment\n                      type: K8sRollingRollback\n                      spec:\n                        timeout: 10m\n              infrastructure:\n                environment:\n                  name: qa\n                  identifier: qa\n                  description: ""\n                  type: PreProduction\n                infrastructureDefinition:\n                  type: KubernetesDirect\n                  spec:\n                    connectorRef: ${input}\n                    namespace: ${input}\n                    releaseName: ${input}\n        - stage:\n            name: test1\n            identifier: test1\n            description: ""\n            type: Deployment\n            spec:\n              execution: {}\n    - stage:\n        name: test2\n        identifier: test2\n        description: ""\n        type: Deployment\n        spec:\n          execution: {}\n'
  },
  metaData: null,
  correlationId: '969ad7a4-0629-4965-8940-1e12c15c504c'
}
