/*
 * Copyright 2021 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

export enum FeatureIdentifier {
  TEST1 = 'TEST1',
  TEST2 = 'TEST2',
  TEST3 = 'TEST3',
  TEST4 = 'TEST4',
  TEST5 = 'TEST5',
  PERSPECTIVES = 'PERSPECTIVES',
  CCM_K8S_CLUSTERS = 'CCM_K8S_CLUSTERS',
  MULTIPLE_ORGANIZATIONS = 'MULTIPLE_ORGANIZATIONS',
  MULTIPLE_PROJECTS = 'MULTIPLE_PROJECTS',
  SECRET_MANAGERS = 'SECRET_MANAGERS',
  TEMPLATE_SERVICE = 'TEMPLATE_SERVICE',
  SAML_SUPPORT = 'SAML_SUPPORT',
  OAUTH_SUPPORT = 'OAUTH_SUPPORT',
  LDAP_SUPPORT = 'LDAP_SUPPORT',
  TWO_FACTOR_AUTH_SUPPORT = 'TWO_FACTOR_AUTH_SUPPORT',
  CUSTOM_ROLES = 'CUSTOM_ROLES',
  CUSTOM_RESOURCE_GROUPS = 'CUSTOM_RESOURCE_GROUPS',
  INTEGRATED_APPROVALS_WITH_HARNESS_UI = 'INTEGRATED_APPROVALS_WITH_HARNESS_UI',
  INTEGRATED_APPROVALS_WITH_JIRA = 'INTEGRATED_APPROVALS_WITH_JIRA',
  INTEGRATED_APPROVALS_WITH_SERVICE_NOW = 'INTEGRATED_APPROVALS_WITH_SERVICE_NOW',
  DEPLOYMENTS = 'DEPLOYMENTS',
  DEPLOYMENTS_PER_MONTH = 'DEPLOYMENTS_PER_MONTH',
  INITIAL_DEPLOYMENTS = 'INITIAL_DEPLOYMENTS',
  BUILDS = 'BUILDS',
  SERVICES = 'SERVICES',
  K8S_BG_SWAP_SERVICES = 'K8S_BG_SWAP_SERVICES',
  K8S_BLUE_GREEN_DEPLOY = 'K8S_BLUE_GREEN_DEPLOY',
  K8S_APPLY = 'K8S_APPLY',
  K8S_DELETE = 'K8S_DELETE',
  K8S_CANARY_DELETE = 'K8S_CANARY_DELETE',
  K8S_ROLLING_DEPLOY = 'K8S_ROLLING_DEPLOY',
  K8S_CANARY_DEPLOY = 'K8S_CANARY_DEPLOY',
  K8S_SCALE = 'K8S_SCALE',
  K8S_ROLLING_ROLLBACK = 'K8S_ROLLING_ROLLBACK',
  TERRAFORM_APPLY = 'TERRAFORM_APPLY',
  TERRAFORM_PLAN = 'TERRAFORM_PLAN',
  TERRAFORM_DESTROY = 'TERRAFORM_DESTROY',
  TERRAFORM_ROLLBACK = 'TERRAFORM_ROLLBACK',
  MAX_TOTAL_BUILDS = 'MAX_TOTAL_BUILDS',
  MAX_BUILDS_PER_MONTH = 'MAX_BUILDS_PER_MONTH',
  TEST_INTELLIGENCE = 'TEST_INTELLIGENCE',
  ACTIVE_COMMITTERS = 'ACTIVE_COMMITTERS',
  DEVELOPERS = 'DEVELOPERS',
  MAUS = 'MONTHLY_ACTIVE_USERS',
  RESTRICTED_AUTOSTOPPING_RULE_CREATION = 'CCM_AUTOSTOPPING_RULES'
}
