export enum FeatureIdentifier {
  TEST1 = 'TEST1',
  TEST2 = 'TEST2',
  TEST3 = 'TEST3',
  MULTIPLE_ORGANIZATIONS = 'MULTIPLE_ORGANIZATIONS',
  MULTIPLE_PROJECTS = 'MULTIPLE_PROJECTS',
  SECRET_MANAGERS = 'SECRET_MANAGERS',
  SAML_SUPPORT = 'SAML_SUPPORT',
  OAUTH_SUPPORT = 'OAUTH_SUPPORT',
  LDAP_SUPPORT = 'LDAP_SUPPORT',
  TWO_FACTOR_AUTH_SUPPORT = 'TWO_FACTOR_AUTH_SUPPORT',
  CUSTOM_ROLES = 'CUSTOM_ROLES'
}
