/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly card: string
  readonly argoLogo: string
  readonly launch: string
  readonly footer: string
  readonly title: string
  readonly main: string
  readonly header: string
  readonly addProviderHeader: string
  readonly expandSearch: string
  readonly providerContainer: string
  readonly content: string
  readonly createConnectorWizard: string
  readonly itemName: string
  readonly itemInfo: string
  readonly formLayout: string
  readonly stepsOverlay: string
  readonly iconConnector: string
  readonly firstep: string
  readonly heading: string
  readonly connectorForm: string
  readonly saveBtn: string
  readonly secondStep: string
  readonly headingStepTwo: string
  readonly customCss: string
  readonly selectedText: string
  readonly selectedCard: string
  readonly recommended: string
  readonly textInfo: string
  readonly delegateWrapper: string
  readonly incluster: string
  readonly howToProceed: string
  readonly radioOption: string
  readonly label: string
  readonly selectDelegate: string
  readonly selectDelegateText: string
  readonly saveSecondStep: string
  readonly intermediateStep: string
  readonly formWrapper: string
  readonly formFields: string
  readonly headingIntermediate: string
  readonly credWrapper: string
  readonly lockIcon: string
  readonly selectAuth: string
  readonly credForm: string
  readonly crossIcon: string
  readonly pagination: string
  readonly pageBody: string
  readonly noPipelineSection: string
  readonly clearFilterText: string
  readonly image: string
  readonly noProviderText: string
  readonly aboutProvider: string
  readonly frameContainer: string
  readonly frameHeader: string
  readonly closeIcon: string
  readonly argoFrame: string
}
export default styles
