/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly wrapper: string
  readonly contentSection: string
  readonly tabHeading: string
  readonly tabSubHeading: string
  readonly sectionCard: string
  readonly sectionCardVariables: string
  readonly section: string
  readonly noPadTop: string
  readonly specTabs: string
  readonly selected: string
  readonly stageSection: string
  readonly stagePopover: string
  readonly noPadVertical: string
  readonly disabled: string
  readonly stageDetails: string
  readonly stageOverridesTab: string
  readonly inputContainer: string
  readonly sideDescription: string
  readonly removeLink: string
  readonly dialogView: string
  readonly squareCardContainer: string
  readonly addDataLinks: string
  readonly fields: string
  readonly contentCard: string
  readonly removeSharedPathButton: string
  readonly fieldsGroup: string
  readonly withoutSpacing: string
  readonly variablesGrid: string
  readonly variableTitle: string
  readonly box: string
  readonly row: string
  readonly secretContainer: string
  readonly editVariable: string
  readonly fixed: string
  readonly icon: string
  readonly configureCodebase: string
  readonly repositoryUrl: string
  readonly predefinedValue: string
  readonly accordionTitle: string
}
export default styles
