export default {
  stepConfiguration: 'Step Configuration',
  advanced: 'Advanced',
  skipCondition: 'Skip Condition',
  specifyConditionToSkipThisStep: 'Specify condition to skip this step',
  ifCondition: 'If condition',
  do: 'Do',
  output: 'Output',
  displayName: 'Display Name',
  failureStrategy: 'Failure Strategy',
  timeout: 'Timeout',
  socketTimeoutMillis: 'Socket Timeout',
  url: 'Url',
  body: 'Body',
  method: 'Method',
  submit: 'Submit',
  stepNameRequired: 'Step Name is required',
  header: 'Header',
  skipDryRun: 'Skip dry run',
  stepLabel: (type: string) => `Step: ${type}`
}
