/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly optionBtns: string
  readonly runForm: string
  readonly editor: string
  readonly content: string
  readonly pipelineHeader: string
  readonly radioGroup: string
  readonly radio: string
  readonly divider: string
  readonly footer: string
  readonly errorsContent: string
  readonly inputsetGrid: string
  readonly treeSidebar: string
  readonly cardCard: string
  readonly inputSetcard: string
  readonly preFlightCheckModal: string
  readonly runFormExecutionView: string
  readonly modalCard: string
  readonly bp3DialogHeader: string
  readonly modalContent: string
  readonly runModalHeader: string
  readonly runModalSubHeading: string
  readonly runModalHeaderTitle: string
  readonly runModalFormContent: string
  readonly runModalFormContentExecutionView: string
  readonly noPipelineInputSetForm: string
  readonly helpSection: string
  readonly helpIcon: string
  readonly runModal: string
  readonly crossIcon: string
  readonly inputSetsUpdatingSpinner: string
  readonly dialog: string
  readonly valueProviderRadio: string
  readonly selectedValueProvider: string
  readonly actionButtons: string
  readonly secondaryButton: string
  readonly footerCheckbox: string
}
export default styles
