export default {
  newInputSet: 'New Input Set',
  VISUAL: 'VISUAL',
  enterTags: 'Enter tags...',
  description: 'Description',
  save: 'Save',
  YAML: 'YAML',
  name: 'Name',
  tags: 'Tags',
  cancel: 'Cancel',
  editTitle: (name: string) => `Edit Input Set: ${name}`,
  editOverlayTitle: (name: string) => `Edit Overlay Input Set: ${name}`,
  nameIsRequired: 'Name is Required field',
  overlaySetName: 'Overlay set name',
  inputSetSaved: 'Input Set Saved',
  overlayInputSetSaved: 'Overlay Input Set Saved',
  commonError: 'Error occurred while fetching/saving the data',
  inputSetName: 'Input set name',
  newOverlayInputSet: 'New Overlay Input Set',
  selectInputSets: 'Select Input Sets',
  selectInputSet: 'Input Sets',
  selectInputSetsHelp:
    'Multiple input sets can be overlaid together. They are applied in the order specified - first one gets applied first, and the subsequent ones get layered in the order and overrides any previously specified values.',
  addInputSet: '+ Add Input Set'
}
