export enum FeatureFlag {
  CDNG_ENABLED = 'CDNG_ENABLED',
  CVNG_ENABLED = 'CVNG_ENABLED',
  CING_ENABLED = 'CING_ENABLED',
  CENG_ENABLED = 'CENG_ENABLED',
  CFNG_ENABLED = 'CFNG_ENABLED',
  NG_CG_TASK_ASSIGNMENT_ISOLATION = 'NG_CG_TASK_ASSIGNMENT_ISOLATION',
  NG_DASHBOARDS = 'NG_DASHBOARDS',
  CD_OVERVIEW_PAGE = 'CD_OVERVIEW_PAGE',
  CI_OVERVIEW_PAGE = 'CI_OVERVIEW_PAGE',
  TI_CALLGRAPH = 'TI_CALLGRAPH',
  NG_TEMPLATES = 'NG_TEMPLATES',
  CE_AS_KUBERNETES_ENABLED = 'CE_AS_KUBERNETES_ENABLED',
  GTM_CD_ENABLED = 'GTM_CD_ENABLED',
  NG_LICENSES_ENABLED = 'NG_LICENSES_ENABLED',
  PLANS_ENABLED = 'PLANS_ENABLED',
  ARGO_PHASE1 = 'ARGO_PHASE1',
  FF_GITSYNC = 'FF_GITSYNC'
}
