export default {
  itemCount: 13,
  pageCount: 1,
  pageIndex: 0,
  pageSize: 15,
  features: [
    {
      archived: false,
      createdAt: 1619223188494,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619223188516,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'hello_world',
      kind: 'boolean',
      modifiedAt: 1619223188494,
      name: 'hello-world',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619221911882,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619221911901,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'fasd',
      kind: 'boolean',
      modifiedAt: 1619221911882,
      name: 'fasd',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619221542068,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619221542086,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'fasdf',
      kind: 'boolean',
      modifiedAt: 1619221542068,
      name: 'fasdf',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619221204641,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619221204658,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'sadfasd',
      kind: 'boolean',
      modifiedAt: 1619221204641,
      name: 'sadfasd',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619220635822,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619220635840,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'sdfgsdfg',
      kind: 'boolean',
      modifiedAt: 1619220635822,
      name: 'sdfgsdfg',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619220447660,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619220447680,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'sdafsadfsad',
      kind: 'boolean',
      modifiedAt: 1619220447660,
      name: 'sdafsadfsad',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619219698551,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619219698577,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'b56',
      kind: 'boolean',
      modifiedAt: 1619219698551,
      name: 'b56',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619219254421,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619219291554,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'fdsg',
      kind: 'boolean',
      modifiedAt: 1619219254421,
      name: 'fdsg',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619219113160,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619219291549,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'dfsg',
      kind: 'boolean',
      modifiedAt: 1619219113160,
      name: 'dfsg',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619218971555,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619219291545,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'b4',
      kind: 'boolean',
      modifiedAt: 1619218971555,
      name: 'b4',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619218552531,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619219291541,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'b3',
      kind: 'boolean',
      modifiedAt: 1619218552531,
      name: 'b3',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619218436570,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619219291536,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'b2',
      kind: 'boolean',
      modifiedAt: 1619218436570,
      name: 'b2',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    },
    {
      archived: false,
      createdAt: 1619218389778,
      defaultOffVariation: 'false',
      defaultOnVariation: 'true',
      envProperties: {
        defaultServe: { variation: 'true' },
        environment: 'sfgsd',
        modifiedAt: 1619219291530,
        offVariation: 'false',
        rules: [],
        state: 'off',
        variationMap: null,
        version: 1
      },
      evaluation: '',
      identifier: 'b1',
      kind: 'boolean',
      modifiedAt: 1619218389778,
      name: 'b1',
      owner: ['current auth user?'],
      permanent: false,
      prerequisites: [],
      project: 'tnhucf1',
      results: [],
      status: { lastAccess: -6795364578871, status: 'never-requested' },
      tags: [],
      variations: [
        { identifier: 'true', name: 'True', value: 'true' },
        { identifier: 'false', name: 'False', value: 'false' }
      ]
    }
  ]
}
