export default {
  status: 'SUCCESS',
  data: {
    totalPages: 2,
    totalItems: 20,
    pageItemCount: 15,
    pageSize: 15,
    content: [
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'foobar',
        name: 'foobar',
        description: '',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'QB',
        name: 'QB',
        description: 'Harness QB environment',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: {
          qb: 'qb',
          'no-restricted': 'no-restricted',
          dev: 'dev',
          testing: 'testing',
          'not-production': 'not-production',
          fun: 'fun'
        },
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'prod',
        name: 'prod',
        description: '',
        color: '#0063F7',
        type: 'Production',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'bat',
        name: 'bat',
        description: '',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'test1',
        name: 'test1',
        description: '',
        color: '#0063F7',
        type: 'Production',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'ffharnessappdemo',
        name: 'ff-harness-app-demo',
        description: '',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'asdfasdfsa',
        name: 'asdfasdfsa',
        description: 'sadfdsafsdfsadfsadfsdafsfsadfsdafdsaf',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: { fsadf: 'fsadf', asdf: 'asdf', asdfff: 'asdfff' },
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'EnvironmentJuan',
        name: 'EnvironmentJuan',
        description: '',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'Another_Production',
        name: 'Another Production',
        description: 'Another production env that can be used',
        color: '#0063F7',
        type: 'Production',
        deleted: false,
        tags: { one: 'one', three: 'three', two: 'two' },
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'Production_Env',
        name: 'Production Env',
        description: 'this is a production environment to run an application do be careful when handling it',
        color: '#0063F7',
        type: 'Production',
        deleted: false,
        tags: { B: 'B', prod: 'prod', tag: 'tag' },
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'new_environment',
        name: 'new environment',
        description: 'this is an environment',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: { new: 'new' },
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'tagged_env',
        name: 'tagged env',
        description: '',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: { tagged: 'tagged' },
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'Another_Environment',
        name: 'Another Environment',
        description: '',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'env42',
        name: 'env42',
        description: 'the 42th',
        color: '#0063F7',
        type: 'PreProduction',
        deleted: false,
        tags: {},
        version: 0
      },
      {
        accountId: 'zEaak-FLS425IEO7OLzMUg',
        orgIdentifier: 'Harness',
        projectIdentifier: 'TNHUFF_PROJECT',
        identifier: 'default',
        name: 'CF Default',
        description: null,
        color: '#0063F7',
        type: 'Production',
        deleted: false,
        tags: {},
        version: 0
      }
    ],
    pageIndex: 0,
    empty: false
  },
  metaData: null,
  correlationId: '3fcb7e6b-8e77-4523-81e5-fdf015b900cc'
}
