/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly rowItem: string
  readonly type: string
  readonly server: string
  readonly instanceTypeViewGrid: string
  readonly instanceTypeNameGrid: string
  readonly card: string
  readonly instanceTable: string
  readonly healthCheckTable: string
  readonly page: string
  readonly instanceSelection: string
  readonly switchFont: string
  readonly helpSidebar: string
  readonly routingTable: string
  readonly dependencyTable: string
  readonly selectCell: string
  readonly configTab: string
  readonly gatewayConfigForm: string
  readonly heading: string
  readonly cardLabel: string
  readonly configStepContainer: string
  readonly stepInfo: string
  readonly title: string
  readonly subTitle: string
  readonly childrenContainer: string
  readonly displayCard: string
  readonly step1Form: string
  readonly formElement: string
  readonly step2Container: string
  readonly radioGroupTitle: string
  readonly radioGroup: string
  readonly clearBtn: string
  readonly asgInstanceSelectionContianer: string
  readonly asgInstanceDetails: string
  readonly asgDetailRow: string
  readonly asgInstanceFormContainer: string
  readonly instanceTypeInput: string
  readonly yamlEditorContainer: string
  readonly titleHelpTextDescription: string
  readonly advancedConfigInput: string
}
export default styles
