fragment CallOut on ComponentPricingPageCallOut {
  title
  desc
}
fragment Plans on ComponentPricingPagePlansZone {
  id
  title
  desc
  img {
    url
    width
    height
  }
  price
  yearlyPrice
  unit
  link
  featureListZone {
    id
    title
    link
  }
  buttonText
  primaryButton
  comingSoon
  priceTips
  priceTerm
  priceTermTips
  yearlyPriceTips
  yearlyPriceTerm
  yearlyPriceTermTips
  support
  featureTitle
  unitTips
}
fragment FeatureCaption on ComponentPricingPageFeatureCaption {
  id
  title
  btnText
  btnLink
  primaryButton
}
fragment FeatureGroup on ComponentPricingPageFeatureGroup {
  id
  title
  detailedFeature {
    id
    title
    link
    communityValue
    communityText
    freeValue
    freeText
    teamValue
    teamText
    enterpriseValue
    enterpriseText
  }
}
fragment Faq on ComponentPricingPageFaq {
  id
  faqTitle
  faqAnswer
  anchor
}

query fetchPlans {
  pricing {
    id
    published_at
    created_at
    updated_at
    hero {
      title
      desc
      subTitle
    }
    ciPlans {
      ...Plans
    }
    ciSaasPlans {
      ...Plans
    }

    cdPlans {
      ...Plans
    }
    ccPlans {
      ...Plans
    }
    ffPlans {
      ...Plans
    }
    chIntelPlans {
      ...Plans
    }

    ciFeatureCaption {
      ...FeatureCaption
    }
    ciFeatureGroup {
      ...FeatureGroup
    }

    cdFeatureCaption {
      ...FeatureCaption
    }
    cdFeatureGroup {
      ...FeatureGroup
    }
    ccFeatureCaption {
      ...FeatureCaption
    }
    ccFeatureGroup {
      ...FeatureGroup
    }
    ffFeatureCaption {
      ...FeatureCaption
    }
    ffFeatureGroup {
      ...FeatureGroup
    }
    ciSaasFeatureCaption {
      ...FeatureCaption
    }
    ciSaasFeatureGroup {
      ...FeatureGroup
    }
    chIntelFeatureCaption {
      ...FeatureCaption
    }
    chIntelFeatureGroup {
      ...FeatureGroup
    }
    cdFaq {
      ...Faq
    }

    ciFaq {
      ...Faq
    }

    ccFaq {
      ...Faq
    }

    ffFaq {
      ...Faq
    }

    caseStudies {
      id
      quote
      client
      link
      clientPic {
        width
        height
        url
      }
    }

    openSource {
      ...CallOut
    }
  }
}
