/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly serviceOverrides: string
  readonly heightStageOverrides: string
  readonly heightStageOverrides2: string
  readonly navigationButtons: string
  readonly overrides: string
  readonly overFlowScroll: string
  readonly alignCenter: string
  readonly contentSection: string
  readonly tabHeading: string
  readonly tabSubHeading: string
  readonly sectionCard: string
  readonly shadow: string
  readonly notwide: string
  readonly nopadleft: string
  readonly propagatedropdown: string
  readonly name: string
  readonly addDataLinks: string
  readonly removeLink: string
  readonly specTabs: string
  readonly selected: string
  readonly overideCheckbox: string
  readonly artifactType: string
  readonly serviceSection: string
  readonly noPadVertical: string
  readonly disabled: string
  readonly serviceSpecType: string
  readonly stageOverridesTab: string
  readonly squareCardContainer: string
  readonly squareCard: string
  readonly stageSelection: string
  readonly stageSelectionGrid: string
  readonly radioColumn: string
  readonly useoverrideCheckbox: string
  readonly propagationPadding: string
}
export default styles
