/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly collapseDiv: string
  readonly labelBold: string
  readonly grid: string
  readonly squareCard: string
  readonly stageCreate: string
  readonly btnSetup: string
  readonly stageSection: string
  readonly stagePopover: string
  readonly tabHeading: string
  readonly noPadVertical: string
  readonly disabled: string
  readonly stageDetails: string
  readonly stageVariables: string
  readonly stageOverridesTab: string
  readonly inputContainer: string
  readonly sideDescription: string
  readonly removeLink: string
  readonly dialogView: string
  readonly squareCardContainer: string
  readonly variablesGrid: string
  readonly variableTitle: string
  readonly box: string
  readonly row: string
  readonly secretContainer: string
  readonly addVariable: string
  readonly editVariable: string
  readonly fixed: string
  readonly icon: string
  readonly toggleDesc: string
  readonly timelineSidebar: string
  readonly sidebarToggle: string
  readonly sidebarToggleContent: string
  readonly hidden: string
  readonly createStageGrid: string
  readonly editStageGrid: string
  readonly contentSection: string
  readonly sectionCard: string
  readonly shadow: string
  readonly notwide: string
  readonly nopadleft: string
}
export default styles
