rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - microfrontends/*
        - '!microfrontends/ChildAppMounter'
        - modules/27-sto/*
        - modules/30-delegates/*
        - modules/30-secrets/*
        - modules/33-auth-settings/*
        - modules/35-connectors/*
        - modules/35-user-profile/*
        - modules/40-gitsync/*
        - modules/45-dashboards/*
        - modules/45-projects-orgs/*
        - modules/70-pipeline/*
        - modules/72-templates-library/*
        - modules/72-triggers/*
        - modules/75-cd/*
        - modules/75-ce/*
        - modules/75-cf/*
        - modules/75-ci/*
        - modules/85-cv/*
        - modules/85-sto-steps/*
        - '@sto/*'
        - '@delegates/*'
        - '@secrets/*'
        - '@auth-settings/*'
        - '@connectors/*'
        - '@user-profile/*'
        - '@gitsync/*'
        - '@dashboards/*'
        - '@projects-orgs/*'
        - '@pipeline/*'
        - '@templates-library/*'
        - '@triggers/*'
        - '@cd/*'
        - '@ce/*'
        - '@cf/*'
        - '@ci/*'
        - '@cv/*'
        - '@sto-steps/*'
      paths:
        - lodash
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead
            of this
        - name: react-router
          message: import from "react-router-dom" instead
        - name: microfrontends
          message: Import from 'microfrontends' is only allowed in child apps
