export enum VerificationStatus {
  IGNORED = 'IGNORED',
  NOT_STARTED = 'NOT_STARTED',
  VERIFICATION_PASSED = 'VERIFICATION_PASSED',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  ERROR = 'ERROR',
  ABORTED = 'ABORTED',
  IN_PROGRESS = 'IN_PROGRESS'
}
