/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly title: string
  readonly checkbox: string
  readonly setupTab: string
  readonly fixedDrawer: string
  readonly page: string
  readonly centerAlignedRadio: string
  readonly radioFont: string
  readonly setupAccessHeading: string
  readonly setupAccessSubHeading: string
  readonly dnsLinkContainer: string
  readonly selectLoadBalancerContainer: string
  readonly helperImage: string
  readonly helpText: string
  readonly loadBalancerSelector: string
  readonly mapDomainHelperText: string
  readonly header: string
  readonly publicAccessibleCheckboxContainer: string
  readonly loadBalancerDnsConfigDialog: string
  readonly configHeading: string
  readonly configInfo: string
  readonly configFormHeader: string
  readonly lbNameInput: string
  readonly customDomainContainer: string
  readonly configFormWrapper: string
  readonly othersHelpTextContainer: string
  readonly helpTextHeader: string
  readonly formFieldRow: string
  readonly uploadCtaContainer: string
  readonly uploadText: string
  readonly certiLabel: string
  readonly flexRow: string
  readonly radioBtn: string
  readonly saveBtn: string
  readonly sshSetupContainer: string
  readonly infoSection: string
  readonly text: string
  readonly selectContainer: string
  readonly titleHelpTextDescription: string
  readonly yamlEditorContainer: string
  readonly switchFont: string
  readonly rowItem: string
  readonly type: string
  readonly server: string
}
export default styles
