/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly mainContainer: string
  readonly graph: string
  readonly widgetWrapper: string
  readonly leftContainer: string
  readonly widget: string
  readonly stats: string
  readonly statsTitle: string
  readonly statsNumber: string
  readonly row: string
  readonly diff: string
  readonly diffNegative: string
  readonly timeSaved: string
  readonly overview: string
  readonly linesWrapper: string
  readonly line: string
  readonly selected: string
  readonly reportsOverview: string
  readonly graphWrapper: string
  readonly graphContainer: string
  readonly overviewResultLabel: string
  readonly executionResult: string
  readonly selectionBreakdown: string
  readonly section: string
  readonly type: string
  readonly number: string
  readonly coverage: string
  readonly columnNames: string
  readonly coverageItem: string
  readonly header: string
  readonly name: string
  readonly commitHash: string
  readonly method: string
  readonly testCasesHeader: string
  readonly rightContainer: string
  readonly testsSelectionBreakdown: string
  readonly testSuite: string
  readonly expanded: string
  readonly headingContainer: string
  readonly testSuiteHeading: string
  readonly splitview: string
  readonly withSeparator: string
  readonly progressBar: string
  readonly testSuiteTable: string
  readonly clickable: string
  readonly rowSelected: string
  readonly testCell: string
  readonly text: string
  readonly failed: string
  readonly select: string
  readonly testPopoverBody: string
  readonly testPopoverHeading: string
  readonly testPopoverDetail: string
  readonly loadingContainer: string
  readonly progress: string
  readonly viewCallgraph: string
  readonly graphLabel: string
  readonly direct: string
  readonly indirect: string
  readonly changed: string
  readonly unchanged: string
  readonly callgraphModal: string
  readonly modalTitle: string
  readonly searchInput: string
  readonly callgraphContainer: string
  readonly callgraphHeader: string
  readonly graphTitle: string
  readonly expandButton: string
  readonly callgraphBody: string
  readonly callgraphLoadingStatus: string
  readonly callgraphError: string
  readonly callgraphTooltip: string
  readonly sourceMethod: string
  readonly methodName: string
  readonly listRow: string
  readonly listName: string
  readonly listValue: string
}
export default styles
