/* eslint-disable */
/**
 * Copyright 2021 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 **/
// this is an auto-generated file, do not update this manually
declare const styles: {
  readonly actionsContainer: string
  readonly activeGroupedIcon: string
  readonly callgraphBody: string
  readonly callgraphContainer: string
  readonly callgraphHeader: string
  readonly callgraphLoadingStatus: string
  readonly callgraphModal: string
  readonly callgraphTooltip: string
  readonly changed: string
  readonly clickable: string
  readonly columnNames: string
  readonly commitHash: string
  readonly coverage: string
  readonly coverageItem: string
  readonly diff: string
  readonly diffNegative: string
  readonly direct: string
  readonly executionResult: string
  readonly expandButton: string
  readonly expanded: string
  readonly failed: string
  readonly failedNumber: string
  readonly findOutMoreBtn: string
  readonly graph: string
  readonly graphContainer: string
  readonly graphLabel: string
  readonly graphTitle: string
  readonly graphWrapper: string
  readonly header: string
  readonly headingContainer: string
  readonly indirect: string
  readonly leftContainer: string
  readonly line: string
  readonly linesWrapper: string
  readonly listIcons: string
  readonly listName: string
  readonly listRow: string
  readonly listValue: string
  readonly loadingContainer: string
  readonly main: string
  readonly mainContainer: string
  readonly method: string
  readonly methodName: string
  readonly modalTitle: string
  readonly name: string
  readonly number: string
  readonly overview: string
  readonly overviewResultLabel: string
  readonly poweredByTi: string
  readonly progress: string
  readonly progressBar: string
  readonly reportsOverview: string
  readonly repositionWarning: string
  readonly rightContainer: string
  readonly row: string
  readonly rowSelected: string
  readonly searchInput: string
  readonly section: string
  readonly select: string
  readonly selected: string
  readonly selectionBreakdown: string
  readonly sortBySelect: string
  readonly sourceMethod: string
  readonly stageOptions: string
  readonly stats: string
  readonly statsNumber: string
  readonly statsTitle: string
  readonly stepOptions: string
  readonly subText: string
  readonly testCasesHeader: string
  readonly testCell: string
  readonly testPopoverBody: string
  readonly testPopoverDetail: string
  readonly testPopoverHeading: string
  readonly testSuite: string
  readonly testSuiteHeading: string
  readonly testSuiteName: string
  readonly testSuiteTable: string
  readonly testsSelectionBreakdown: string
  readonly text: string
  readonly tiCallToActionWrapper: string
  readonly tiUpgradeImage: string
  readonly timeSaved: string
  readonly type: string
  readonly unchanged: string
  readonly upgradeRequiredWrapper: string
  readonly viewCallgraph: string
  readonly widget: string
  readonly widgetWrapper: string
  readonly withSeparator: string
}
export default styles
