export type ResourceGroup = Record<string, string>
export type ResourceGroupSelection = Record<string, boolean>
export enum ResourceType {
  ACCOUNT = 'ACCOUNT',
  ORGANIZATION = 'ORGANIZATION',
  PROJECT = 'PROJECT',
  SECRET = 'SECRET',
  CONNECTOR = 'CONNECTOR',
  PIPELINE = 'PIPELINE',
  SERVICE = 'SERVICE',
  ENVIRONMENT = 'ENVIRONMENT',
  USER = 'USER',
  USERGROUP = 'USERGROUP',
  SERVICEACCOUNT = 'SERVICEACCOUNT',
  ROLE = 'ROLE',
  RESOURCEGROUP = 'RESOURCEGROUP',
  AUTHSETTING = 'AUTHSETTING',
  DELEGATE = 'DELEGATE',
  FEATUREFLAG = 'FEATUREFLAG',
  TARGETGROUP = 'TARGETGROUP',
  TARGET = 'TARGET',
  DELEGATECONFIGURATION = 'DELEGATECONFIGURATION',
  DASHBOARDS = 'DASHBOARDS',
  TEMPLATE = 'TEMPLATE',
  MONITOREDSERVICE = 'MONITOREDSERVICE',
  SLO = 'SLO'
}

export enum ResourceCategory {
  SHARED_RESOURCES = 'SHARED_RESOURCES',
  ADMINSTRATIVE_FUNCTIONS = 'ADMINSTRATIVE_FUNCTIONS',
  FEATUREFLAG_FUNCTIONS = 'FEATUREFLAG_FUNCTIONS',
  CHANGEINTELLIGENCE_FUNCTION = 'CHANGEINTELLIGENCE_FUNCTION'
}
