export enum YamlEntity {
  CONNECTOR = 'CONNECTOR',
  PIPELINE = 'PIPELINE',
  SECRET = 'SECRET',
  ENVIRONMENT = 'ENVIRONMENT',
  INPUT_SET = 'INPUT_SET',
  NOTIFICATION = 'NOTIFICATION',
  STAGE = 'STAGE',
  STEP = 'STEP',
  TRIGGER = 'TRIGGER'
}
