/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly pageheader: string
  readonly separator: string
  readonly table: string
  readonly gitFilter: string
  readonly pipelineCard: string
  readonly pipelineNameSections: string
  readonly pipelineTitle: string
  readonly menu: string
  readonly sectionMargin: string
  readonly sectionBorder: string
  readonly pipelineGitDetails: string
  readonly pipelineName: string
  readonly serviceLabel: string
  readonly serviceName: string
  readonly runPipelineBtn: string
  readonly viewExecutionBtn: string
  readonly runPipelineListBtn: string
  readonly topHeaderFields: string
  readonly sortSelector: string
  readonly tagRow: string
  readonly cardTags: string
  readonly header: string
  readonly expandSearch: string
  readonly activityChart: string
  readonly lastExecutionTs: string
  readonly clickable: string
  readonly actionButton: string
  readonly gridLayout: string
  readonly pagination: string
  readonly pageBody: string
  readonly loading: string
  readonly noData: string
  readonly noPipelineSection: string
  readonly clearFilterText: string
  readonly image: string
  readonly noPipelineText: string
  readonly aboutPipeline: string
  readonly confirmText: string
}
export default styles
