/* Generated by restful-react */

import React from 'react'
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react'

import { getConfig } from '../config'
export const SPEC_VERSION = '1.0.0'
export interface ApiKey {
  /**
   * The Key will be shown only on create. On subsequemt GET calls, only the masked APIKeys will be returned
   */
  apiKey: string
  identifier: string
  name: string
  type: 'Server' | 'Client'
}

export type ApiKeys = Pagination & {
  apiKeys?: ApiKey[]
}

export interface AuditTrail {
  action: string
  actor: string
  comment: string
  enviroment?: string
  executedOn: number
  instructionSet: { [key: string]: any }[]
  objectAfter: string
  objectBefore: string
  objectIdentifier: string
  objectType: string
  project: string
  status: string
}

export type AuditTrails = Pagination & {
  auditTrails?: AuditTrail[]
}

export interface Clause {
  attribute: string
  id: string
  negate: boolean
  op: string
  values: string[]
}

export interface Distribution {
  bucketBy: string
  variations: WeightedVariation[]
}

export interface Environment {
  apiKeys: ApiKeys
  description?: string
  identifier: string
  name: string
  project: string
  tags?: Tag[]
}

export interface Environments {
  environments?: Environment[]
}

export interface Error {
  code: string
  message: string
}

export interface Feature {
  archived: boolean
  createdAt: number
  defaultOffVariation: string
  defaultOnVariation: string
  description?: string
  envProperties?: {
    defaultServe: Serve
    environment: string
    modifiedAt: number
    offVariation: string
    rules?: ServingRule[]
    state: FeatureState
    variationMap?: VariationMap[]
    version?: number
  }
  evaluation?: string
  evaluationIdentifier?: string
  identifier: string
  kind: 'boolean' | 'int' | 'string' | 'json'
  modifiedAt: number
  name: string
  owner?: string[]
  permanent: boolean
  prerequisites?: Prerequisite[]
  project: string
  results?: Results[]
  status?: FeatureStatus
  tags?: Tag[]
  variations: Variation[]
}

export interface FeatureEvaluation {
  count?: number
  date?: number
  variationIdentifier?: string
  variationName?: string
}

export interface FeatureEvaluations {
  evaluations?: FeatureEvaluation[]
}

export type FeatureState = 'on' | 'off'

export interface FeatureStatus {
  lastAccess: number
  status: 'active' | 'inactive' | 'never-requested'
}

export type Features = Pagination & {
  features?: Feature[]
}

export interface FlagBasicInfo {
  identifier: string
  name: string
}

export type FlagBasicInfos = Pagination & {
  featureFlags?: FlagBasicInfo[]
}

/**
 * A pair of object id and object body
 */
export interface ObjectSnapshot {
  id: string
  value?: { [key: string]: any }
}

export interface ObjectSnapshots {
  objectsnapshots?: ObjectSnapshot[]
}

export interface Pagination {
  itemCount: number
  pageCount: number
  pageIndex: number
  pageSize: number
  version?: number
}

export type PatchInstruction = {
  /**
   * The name of the modification you would like to perform on a resource.
   */
  kind: string
  parameters: { [key: string]: any }
}[]

export interface PatchOperation {
  comment?: string
  /**
   * Time of execution in unix epoch milliseconds when the scheduled changes will be applied
   */
  executionTime?: number
  instructions: PatchInstruction
}

export interface Prerequisite {
  feature: string
  variations: string[]
}

export interface Project {
  description?: string
  identifier: string
  name: string
  tags?: Tag[]
}

export interface Projects {
  itemCount?: number
  pageCount?: number
  pageIndex?: number
  pageSize?: number
  projects?: Project[]
}

export interface Results {
  count: number
  variationIdentifier: string
  variationName: string
}

export interface Segment {
  createdAt?: number
  environment?: string
  excluded?: Target[]
  /**
   * Unique identifier for the segment.
   */
  identifier: string
  included?: Target[]
  modifiedAt?: number
  /**
   * Name of the segment.
   */
  name: string
  /**
   * An array of rules that can cause a user to be included in this segment.
   */
  rules?: Clause[]
  tags?: Tag[]
  version?: number
}

export interface SegmentFlag {
  description?: string
  environment: string
  identifier: string
  name: string
  project: string
  type: 'DIRECT' | 'CONDITION'
  variation: string
}

export type Segments = Pagination & {
  segments?: Segment[]
}

export interface Serve {
  distribution?: Distribution
  variation?: string
}

export interface ServingRule {
  clauses: Clause[]
  priority: number
  ruleId: string
  serve: Serve
}

export type Status = 'SUCCESS' | 'FAILURE' | 'ERROR'

/**
 * A name and value pair.
 */
export interface Tag {
  name: string
  value?: string
}

export interface Target {
  account: string
  anonymous?: boolean
  attributes?: { [key: string]: any }
  createdAt?: number
  environment: string
  identifier: string
  name: string
  org: string
  project: string
  segments?: Segment[]
}

export interface TargetAndSegment {
  identifier?: string
  name?: string
  type: 'target' | 'segment'
}

export interface TargetDetail {
  excludedSegments?: TargetDetailSegment[]
  identifier?: string
  includedSegments?: TargetDetailSegment[]
  ruleSegments?: TargetDetailSegment[]
}

export interface TargetDetailSegment {
  identifier?: string
  name?: string
}

export interface TargetMap {
  identifier?: string
  name: string
}

export type Targets = Pagination & {
  targets?: Target[]
}

export type TargetsAndSegments = Pagination & {
  entities?: TargetAndSegment[]
}

export type TargetsAndSegmentsInfo = {
  entities?: TargetAndSegment[]
}

export interface Variation {
  description?: string
  identifier: string
  name?: string
  value: string
}

export interface VariationMap {
  targetSegments?: string[]
  targets?: TargetMap[]
  variation: string
}

export interface WeightedVariation {
  variation: string
  weight: number
}

export type APIKeyRequestRequestBody = {
  description?: string
  expiredAt?: number
  identifier: string
  name: string
  type: 'Server' | 'Client'
}

export interface APIKeyUpdateRequestRequestBody {
  description?: string
  expiredAt?: number
  name?: string
}

export interface EnvironmentRequestRequestBody {
  description?: string
  identifier: string
  name: string
  project: string
  tags?: Tag[]
}

export type FeatureFlagRequestRequestBody = {
  archived?: boolean
  defaultOffVariation: string
  defaultOnVariation: string
  description?: string
  identifier: string
  kind: 'boolean' | 'int' | 'string' | 'json'
  name: string
  owner?: string
  permanent: boolean
  prerequisites?: Prerequisite[]
  project: string
  tags?: Tag[]
  variations: Variation[]
}

export type FeaturePatchRequestRequestBody = PatchOperation

export interface ProjectRequestRequestBody {
  description?: string
  identifier: string
  name: string
  tags?: Tag[]
}

export type SegmentPatchRequestRequestBody = PatchOperation

export interface SegmentRequestRequestBody {
  environment: string
  excluded?: string[]
  identifier?: string
  included?: string[]
  /**
   * Name of the target segment.
   */
  name: string
  project: string
  /**
   * An array of rules that can cause a user to be included in this segment.
   */
  rules?: Clause[]
  tags?: Tag[]
}

export type TargetPatchRequestRequestBody = PatchOperation

export type TargetRequestRequestBody = Target

/**
 * Created
 */
export type APIKeyResponseResponse = ApiKey

/**
 * OK
 */
export type APIKeysResponseResponse = ApiKeys

/**
 * OK
 */
export interface AuditTrailResponseResponse {
  correlationId?: string
  data?: AuditTrails
  metaData?: { [key: string]: any }
  status?: Status
}

/**
 * OK
 */
export type AvailableFlagResponseResponse = FlagBasicInfos

/**
 * Bad request
 */
export type BadRequestResponse = Error

/**
 * The specified resource already exists
 */
export type ConflictResponse = Error

/**
 * OK
 */
export interface EnvironmentResponseResponse {
  correlationId?: string
  data?: Environment
  metaData?: { [key: string]: any }
  status?: Status
}

/**
 * OK
 */
export interface EnvironmentsResponseResponse {
  correlationId: string
  data: Environments
  metaData?: { [key: string]: any }
  status: Status
}

/**
 * OK
 */
export type FeatureEvaluationsResponseResponse = FeatureEvaluations

/**
 * OK
 */
export type FeatureResponseResponse = Feature

/**
 * OK
 */
export type FeaturesResponseResponse = Features

/**
 * Internal server error
 */
export type InternalServerErrorResponse = Error

/**
 * The specified resource was not found
 */
export type NotFoundResponse = Error

/**
 * OK
 */
export interface ObjectSnapshotResponseResponse {
  correlationId?: string
  data?: ObjectSnapshots
  metaData?: { [key: string]: any }
  status?: Status
}

/**
 * OK
 */
export interface ProjectResponseResponse {
  correlationId?: string
  data?: Project
  metaData?: { [key: string]: any }
  status?: Status
}

/**
 * OK
 */
export interface ProjectsResponseResponse {
  correlationId?: string
  data?: Projects
  metaData?: { [key: string]: any }
  status?: Status
}

/**
 * OK
 */
export type SegmentFlagsResponseResponse = SegmentFlag[]

/**
 * OK
 */
export type SegmentResponseResponse = Segment

/**
 * OK
 */
export type SegmentsResponseResponse = Segments

/**
 * OK
 */
export type TargetAttributesResponse = string[]

/**
 * OK
 */
export type TargetDetailResponseResponse = TargetDetail

/**
 * OK
 */
export type TargetResponseResponse = Target

/**
 * OK
 */
export type TargetSegmentResponseResponse = TargetsAndSegments

/**
 * OK
 */
export type TargetSegmentsInfoResponseResponse = TargetsAndSegmentsInfo

/**
 * OK
 */
export type TargetsResponseResponse = Targets

/**
 * Unauthenticated
 */
export type UnauthenticatedResponse = Error

/**
 * Unauthorized
 */
export type UnauthorizedResponse = Error

export interface GetAllAPIKeysQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
}

export type GetAllAPIKeysProps = Omit<
  GetProps<
    APIKeysResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllAPIKeysQueryParams,
    void
  >,
  'path'
>

/**
 * Get all APiKeys for an environment
 *
 * Get all the apiKeys for an environment
 */
export const GetAllAPIKeys = (props: GetAllAPIKeysProps) => (
  <Get<
    APIKeysResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllAPIKeysQueryParams,
    void
  >
    path={`/admin/apikey`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllAPIKeysProps = Omit<
  UseGetProps<
    APIKeysResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllAPIKeysQueryParams,
    void
  >,
  'path'
>

/**
 * Get all APiKeys for an environment
 *
 * Get all the apiKeys for an environment
 */
export const useGetAllAPIKeys = (props: UseGetAllAPIKeysProps) =>
  useGet<
    APIKeysResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllAPIKeysQueryParams,
    void
  >(`/admin/apikey`, { base: getConfig('cf'), ...props })

export interface AddAPIKeyQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Environment
   */
  environment: string
  /**
   * Project
   */
  project: string
}

export type AddAPIKeyProps = Omit<
  MutateProps<
    APIKeyResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    AddAPIKeyQueryParams,
    APIKeyRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Add an API Key to environment.
 *
 * Used to create a key in an environment. The Key will be shown only on create. On subsequemt GET calls, only the masked APIKeys will be returned
 */
export const AddAPIKey = (props: AddAPIKeyProps) => (
  <Mutate<
    APIKeyResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    AddAPIKeyQueryParams,
    APIKeyRequestRequestBody,
    void
  >
    verb="POST"
    path={`/admin/apikey`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseAddAPIKeyProps = Omit<
  UseMutateProps<
    APIKeyResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    AddAPIKeyQueryParams,
    APIKeyRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Add an API Key to environment.
 *
 * Used to create a key in an environment. The Key will be shown only on create. On subsequemt GET calls, only the masked APIKeys will be returned
 */
export const useAddAPIKey = (props: UseAddAPIKeyProps) =>
  useMutate<
    APIKeyResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    AddAPIKeyQueryParams,
    APIKeyRequestRequestBody,
    void
  >('POST', `/admin/apikey`, { base: getConfig('cf'), ...props })

export interface DeleteApiKeyQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type DeleteApiKeyProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete APIKey
 *
 * Used to delete an APIKey
 */
export const DeleteApiKey = (props: DeleteApiKeyProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >
    verb="DELETE"
    path={`/admin/apikey`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteApiKeyProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete APIKey
 *
 * Used to delete an APIKey
 */
export const useDeleteApiKey = (props: UseDeleteApiKeyProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >('DELETE', `/admin/apikey`, { base: getConfig('cf'), ...props })

export interface GetAPIKeyQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export interface GetAPIKeyPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetAPIKeyProps = Omit<
  GetProps<
    APIKeyResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAPIKeyQueryParams,
    GetAPIKeyPathParams
  >,
  'path'
> &
  GetAPIKeyPathParams

/**
 * Get all APiKeys for an environment
 *
 * Get all the apiKeys for an environment
 */
export const GetAPIKey = ({ identifier, ...props }: GetAPIKeyProps) => (
  <Get<
    APIKeyResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAPIKeyQueryParams,
    GetAPIKeyPathParams
  >
    path={`/admin/apikey/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAPIKeyProps = Omit<
  UseGetProps<
    APIKeyResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAPIKeyQueryParams,
    GetAPIKeyPathParams
  >,
  'path'
> &
  GetAPIKeyPathParams

/**
 * Get all APiKeys for an environment
 *
 * Get all the apiKeys for an environment
 */
export const useGetAPIKey = ({ identifier, ...props }: UseGetAPIKeyProps) =>
  useGet<
    APIKeyResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAPIKeyQueryParams,
    GetAPIKeyPathParams
  >((paramsInPath: GetAPIKeyPathParams) => `/admin/apikey/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface UpdateAPIKeyQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export interface UpdateAPIKeyPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type UpdateAPIKeyProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UpdateAPIKeyQueryParams,
    APIKeyUpdateRequestRequestBody,
    UpdateAPIKeyPathParams
  >,
  'path' | 'verb'
> &
  UpdateAPIKeyPathParams

/**
 * Add an API Key to environment.
 *
 * Used to create a key in an environment.
 */
export const UpdateAPIKey = ({ identifier, ...props }: UpdateAPIKeyProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UpdateAPIKeyQueryParams,
    APIKeyUpdateRequestRequestBody,
    UpdateAPIKeyPathParams
  >
    verb="PUT"
    path={`/admin/apikey/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseUpdateAPIKeyProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UpdateAPIKeyQueryParams,
    APIKeyUpdateRequestRequestBody,
    UpdateAPIKeyPathParams
  >,
  'path' | 'verb'
> &
  UpdateAPIKeyPathParams

/**
 * Add an API Key to environment.
 *
 * Used to create a key in an environment.
 */
export const useUpdateAPIKey = ({ identifier, ...props }: UseUpdateAPIKeyProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UpdateAPIKeyQueryParams,
    APIKeyUpdateRequestRequestBody,
    UpdateAPIKeyPathParams
  >('PUT', (paramsInPath: UpdateAPIKeyPathParams) => `/admin/apikey/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetAuditByParamsQueryParams {
  /**
   * Environment
   */
  environment?: string
  /**
   * Project
   */
  project?: string
  /**
   * Object Type (FeatureActivation Or Segment)
   */
  objectType: 'FeatureActivation' | 'Segment'
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Start Time
   */
  startTime?: number
  /**
   * End Time
   */
  endTime?: number
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * Actor
   */
  actor?: string
  /**
   * Action
   */
  action?: ('FeatureActivationCreated' | 'SegmentCreated' | 'FeatureActivationPatched')[]
  /**
   * Identifier of the entity
   */
  identifier?: string
  /**
   * SortOrder
   */
  sortOrder?: 'ASC' | 'DESC'
  /**
   * SortByField
   */
  sortByField?: 'executed_on' | 'actor' | 'action'
}

export type GetAuditByParamsProps = Omit<
  GetProps<
    AuditTrailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAuditByParamsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve Audit
 *
 * Used to retrieve audit details based on environment, project, object type, organization, account and timestamp
 */
export const GetAuditByParams = (props: GetAuditByParamsProps) => (
  <Get<
    AuditTrailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAuditByParamsQueryParams,
    void
  >
    path={`/admin/audit`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAuditByParamsProps = Omit<
  UseGetProps<
    AuditTrailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAuditByParamsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve Audit
 *
 * Used to retrieve audit details based on environment, project, object type, organization, account and timestamp
 */
export const useGetAuditByParams = (props: UseGetAuditByParamsProps) =>
  useGet<
    AuditTrailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAuditByParamsQueryParams,
    void
  >(`/admin/audit`, { base: getConfig('cf'), ...props })

export interface GetAllEnvironmentsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: 'name' | 'identifier' | 'archived' | 'kind' | 'modifiedAt'
}

export type GetAllEnvironmentsProps = Omit<
  GetProps<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all environments in a project
 *
 * Get all the environments in a project
 */
export const GetAllEnvironments = (props: GetAllEnvironmentsProps) => (
  <Get<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >
    path={`/admin/environments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllEnvironmentsProps = Omit<
  UseGetProps<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all environments in a project
 *
 * Get all the environments in a project
 */
export const useGetAllEnvironments = (props: UseGetAllEnvironmentsProps) =>
  useGet<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >(`/admin/environments`, { base: getConfig('cf'), ...props })

export interface CreateEnvironmentQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type CreateEnvironmentProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Environment.
 *
 * Used to create an environment.
 */
export const CreateEnvironment = (props: CreateEnvironmentProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    void
  >
    verb="POST"
    path={`/admin/environments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateEnvironmentProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Environment.
 *
 * Used to create an environment.
 */
export const useCreateEnvironment = (props: UseCreateEnvironmentProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    void
  >('POST', `/admin/environments`, { base: getConfig('cf'), ...props })

export interface DeleteEnvironmentQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type DeleteEnvironmentProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Environment
 *
 * Used to delete an Environment
 */
export const DeleteEnvironment = (props: DeleteEnvironmentProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >
    verb="DELETE"
    path={`/admin/environments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteEnvironmentProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Environment
 *
 * Used to delete an Environment
 */
export const useDeleteEnvironment = (props: UseDeleteEnvironmentProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >('DELETE', `/admin/environments`, { base: getConfig('cf'), ...props })

export interface GetEnvironmentQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export interface GetEnvironmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetEnvironmentProps = Omit<
  GetProps<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >,
  'path'
> &
  GetEnvironmentPathParams

/**
 * Get Environment by an identifier.
 *
 * Used to retrieve an Environment by the Environment Identifier.
 */
export const GetEnvironment = ({ identifier, ...props }: GetEnvironmentProps) => (
  <Get<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >
    path={`/admin/environments/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetEnvironmentProps = Omit<
  UseGetProps<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >,
  'path'
> &
  GetEnvironmentPathParams

/**
 * Get Environment by an identifier.
 *
 * Used to retrieve an Environment by the Environment Identifier.
 */
export const useGetEnvironment = ({ identifier, ...props }: UseGetEnvironmentProps) =>
  useGet<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >((paramsInPath: GetEnvironmentPathParams) => `/admin/environments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface ModifyEnvironmentQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
}

export interface ModifyEnvironmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type ModifyEnvironmentProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >,
  'path' | 'verb'
> &
  ModifyEnvironmentPathParams

/**
 * Modify an Environment.
 *
 * Used to modify an Environment.
 */
export const ModifyEnvironment = ({ identifier, ...props }: ModifyEnvironmentProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >
    verb="PUT"
    path={`/admin/environments/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseModifyEnvironmentProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >,
  'path' | 'verb'
> &
  ModifyEnvironmentPathParams

/**
 * Modify an Environment.
 *
 * Used to modify an Environment.
 */
export const useModifyEnvironment = ({ identifier, ...props }: UseModifyEnvironmentProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >('PUT', (paramsInPath: ModifyEnvironmentPathParams) => `/admin/environments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetAllFeaturesQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment?: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: 'name' | 'identifier' | 'archived' | 'kind' | 'modifiedAt'
  /**
   * Name of the field
   */
  name?: string
  /**
   * Identifier of the field
   */
  identifier?: string
  /**
   * Status of the feature flag
   */
  archived?: boolean
  /**
   * Kind of the feature flag
   */
  kind?: 'json' | 'string' | 'int' | 'boolean'
  /**
   * Identifier of a target
   */
  targetIdentifier?: string
  /**
   * Parameter to indicate if metrics data is requested in response
   */
  metrics?: boolean
}

export type GetAllFeaturesProps = Omit<
  GetProps<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all feature activations.
 *
 * Used to retrieve all feature activations for certain account id.
 */
export const GetAllFeatures = (props: GetAllFeaturesProps) => (
  <Get<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >
    path={`/admin/features`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllFeaturesProps = Omit<
  UseGetProps<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all feature activations.
 *
 * Used to retrieve all feature activations for certain account id.
 */
export const useGetAllFeatures = (props: UseGetAllFeaturesProps) =>
  useGet<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >(`/admin/features`, { base: getConfig('cf'), ...props })

export interface CreateFeatureFlagQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type CreateFeatureFlagProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateFeatureFlagQueryParams,
    FeatureFlagRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create a feature
 *
 * Create a feature flag.
 */
export const CreateFeatureFlag = (props: CreateFeatureFlagProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateFeatureFlagQueryParams,
    FeatureFlagRequestRequestBody,
    void
  >
    verb="POST"
    path={`/admin/features`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateFeatureFlagProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateFeatureFlagQueryParams,
    FeatureFlagRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create a feature
 *
 * Create a feature flag.
 */
export const useCreateFeatureFlag = (props: UseCreateFeatureFlagProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateFeatureFlagQueryParams,
    FeatureFlagRequestRequestBody,
    void
  >('POST', `/admin/features`, { base: getConfig('cf'), ...props })

export interface DeleteFeatureFlagQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
}

export type DeleteFeatureFlagProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete a feature
 *
 * Delete feature with certain identifier and account id.
 */
export const DeleteFeatureFlag = (props: DeleteFeatureFlagProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >
    verb="DELETE"
    path={`/admin/features`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteFeatureFlagProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete a feature
 *
 * Delete feature with certain identifier and account id.
 */
export const useDeleteFeatureFlag = (props: UseDeleteFeatureFlagProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >('DELETE', `/admin/features`, { base: getConfig('cf'), ...props })

export interface GetFeatureFlagQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment?: string
}

export interface GetFeatureFlagPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetFeatureFlagProps = Omit<
  GetProps<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >,
  'path'
> &
  GetFeatureFlagPathParams

/**
 * Retrieve a feature
 *
 * Retrieve certain feature flag with certain identifier and account id.
 */
export const GetFeatureFlag = ({ identifier, ...props }: GetFeatureFlagProps) => (
  <Get<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >
    path={`/admin/features/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetFeatureFlagProps = Omit<
  UseGetProps<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >,
  'path'
> &
  GetFeatureFlagPathParams

/**
 * Retrieve a feature
 *
 * Retrieve certain feature flag with certain identifier and account id.
 */
export const useGetFeatureFlag = ({ identifier, ...props }: UseGetFeatureFlagProps) =>
  useGet<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >((paramsInPath: GetFeatureFlagPathParams) => `/admin/features/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface PatchFeatureQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment?: string
}

export interface PatchFeaturePathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type PatchFeatureProps = Omit<
  MutateProps<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureQueryParams,
    FeaturePatchRequestRequestBody,
    PatchFeaturePathParams
  >,
  'path' | 'verb'
> &
  PatchFeaturePathParams

/**
 * Modify a feature using instructions
 *
 * Modify feature flag with certain identifier and account id.
 */
export const PatchFeature = ({ identifier, ...props }: PatchFeatureProps) => (
  <Mutate<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureQueryParams,
    FeaturePatchRequestRequestBody,
    PatchFeaturePathParams
  >
    verb="PATCH"
    path={`/admin/features/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UsePatchFeatureProps = Omit<
  UseMutateProps<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureQueryParams,
    FeaturePatchRequestRequestBody,
    PatchFeaturePathParams
  >,
  'path' | 'verb'
> &
  PatchFeaturePathParams

/**
 * Modify a feature using instructions
 *
 * Modify feature flag with certain identifier and account id.
 */
export const usePatchFeature = ({ identifier, ...props }: UsePatchFeatureProps) =>
  useMutate<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureQueryParams,
    FeaturePatchRequestRequestBody,
    PatchFeaturePathParams
  >('PATCH', (paramsInPath: PatchFeaturePathParams) => `/admin/features/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetFeatureEvaluationsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment?: string
  /**
   * Start Time
   */
  startTime?: number
  /**
   * End Time
   */
  endTime?: number
}

export interface GetFeatureEvaluationsPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetFeatureEvaluationsProps = Omit<
  GetProps<
    FeatureEvaluationsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureEvaluationsQueryParams,
    GetFeatureEvaluationsPathParams
  >,
  'path'
> &
  GetFeatureEvaluationsPathParams

/**
 * Retrieve all feature evaluations.
 *
 * Used to retrieve metrics on how often a feature has been evaluated
 */
export const GetFeatureEvaluations = ({ identifier, ...props }: GetFeatureEvaluationsProps) => (
  <Get<
    FeatureEvaluationsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureEvaluationsQueryParams,
    GetFeatureEvaluationsPathParams
  >
    path={`/admin/features/${identifier}/evaluations`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetFeatureEvaluationsProps = Omit<
  UseGetProps<
    FeatureEvaluationsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureEvaluationsQueryParams,
    GetFeatureEvaluationsPathParams
  >,
  'path'
> &
  GetFeatureEvaluationsPathParams

/**
 * Retrieve all feature evaluations.
 *
 * Used to retrieve metrics on how often a feature has been evaluated
 */
export const useGetFeatureEvaluations = ({ identifier, ...props }: UseGetFeatureEvaluationsProps) =>
  useGet<
    FeatureEvaluationsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureEvaluationsQueryParams,
    GetFeatureEvaluationsPathParams
  >((paramsInPath: GetFeatureEvaluationsPathParams) => `/admin/features/${paramsInPath.identifier}/evaluations`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetOSByIdPathParams {
  /**
   * Unique identifiers for the object in the API.
   */
  identifiers: string[]
}

export type GetOSByIdProps = Omit<
  GetProps<
    ObjectSnapshotResponseResponse | void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetOSByIdPathParams
  >,
  'path'
> &
  GetOSByIdPathParams

/**
 * Retrieve Object Snapshot
 *
 * Used to retrieve the json body of the object from the object snapshot table
 */
export const GetOSById = ({ identifiers, ...props }: GetOSByIdProps) => (
  <Get<
    ObjectSnapshotResponseResponse | void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetOSByIdPathParams
  >
    path={`/admin/objects/${identifiers}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetOSByIdProps = Omit<
  UseGetProps<
    ObjectSnapshotResponseResponse | void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetOSByIdPathParams
  >,
  'path'
> &
  GetOSByIdPathParams

/**
 * Retrieve Object Snapshot
 *
 * Used to retrieve the json body of the object from the object snapshot table
 */
export const useGetOSById = ({ identifiers, ...props }: UseGetOSByIdProps) =>
  useGet<
    ObjectSnapshotResponseResponse | void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetOSByIdPathParams
  >((paramsInPath: GetOSByIdPathParams) => `/admin/objects/${paramsInPath.identifiers}`, {
    base: getConfig('cf'),
    pathParams: { identifiers },
    ...props
  })

export interface GetAllProjectsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: 'name' | 'identifier' | 'archived' | 'kind' | 'modifiedAt'
}

export type GetAllProjectsProps = Omit<
  GetProps<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all projects
 *
 * Get all projects
 */
export const GetAllProjects = (props: GetAllProjectsProps) => (
  <Get<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >
    path={`/admin/projects`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllProjectsProps = Omit<
  UseGetProps<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all projects
 *
 * Get all projects
 */
export const useGetAllProjects = (props: UseGetAllProjectsProps) =>
  useGet<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >(`/admin/projects`, { base: getConfig('cf'), ...props })

export interface CreateProjectQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type CreateProjectProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateProjectQueryParams,
    ProjectRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Project.
 *
 * Used to create a project.
 */
export const CreateProject = (props: CreateProjectProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateProjectQueryParams,
    ProjectRequestRequestBody,
    void
  >
    verb="POST"
    path={`/admin/projects`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateProjectProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateProjectQueryParams,
    ProjectRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Project.
 *
 * Used to create a project.
 */
export const useCreateProject = (props: UseCreateProjectProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateProjectQueryParams,
    ProjectRequestRequestBody,
    void
  >('POST', `/admin/projects`, { base: getConfig('cf'), ...props })

export interface DeleteProjectQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type DeleteProjectProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteProjectQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Project
 *
 * Used to delete project
 */
export const DeleteProject = (props: DeleteProjectProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteProjectQueryParams,
    string,
    void
  >
    verb="DELETE"
    path={`/admin/projects`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteProjectProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteProjectQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Project
 *
 * Used to delete project
 */
export const useDeleteProject = (props: UseDeleteProjectProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteProjectQueryParams,
    string,
    void
  >('DELETE', `/admin/projects`, { base: getConfig('cf'), ...props })

export interface GetProjectQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export interface GetProjectPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetProjectProps = Omit<
  GetProps<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetProjectQueryParams,
    GetProjectPathParams
  >,
  'path'
> &
  GetProjectPathParams

/**
 * Get Project by an key.
 *
 * Used to retrieve project by the projectKey.
 */
export const GetProject = ({ identifier, ...props }: GetProjectProps) => (
  <Get<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetProjectQueryParams,
    GetProjectPathParams
  >
    path={`/admin/projects/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetProjectProps = Omit<
  UseGetProps<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetProjectQueryParams,
    GetProjectPathParams
  >,
  'path'
> &
  GetProjectPathParams

/**
 * Get Project by an key.
 *
 * Used to retrieve project by the projectKey.
 */
export const useGetProject = ({ identifier, ...props }: UseGetProjectProps) =>
  useGet<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetProjectQueryParams,
    GetProjectPathParams
  >((paramsInPath: GetProjectPathParams) => `/admin/projects/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface ModifyProjectQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export interface ModifyProjectPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type ModifyProjectProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyProjectQueryParams,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >,
  'path' | 'verb'
> &
  ModifyProjectPathParams

/**
 * Modify a Project.
 *
 * Used to modify a project.
 */
export const ModifyProject = ({ identifier, ...props }: ModifyProjectProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyProjectQueryParams,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >
    verb="PUT"
    path={`/admin/projects/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseModifyProjectProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyProjectQueryParams,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >,
  'path' | 'verb'
> &
  ModifyProjectPathParams

/**
 * Modify a Project.
 *
 * Used to modify a project.
 */
export const useModifyProject = ({ identifier, ...props }: UseModifyProjectProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyProjectQueryParams,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >('PUT', (paramsInPath: ModifyProjectPathParams) => `/admin/projects/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetAllSegmentsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Environment
   */
  environment: string
  /**
   * Project
   */
  project: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: 'name' | 'identifier' | 'archived' | 'kind' | 'modifiedAt'
  /**
   * Name of the field
   */
  name?: string
  /**
   * Identifier of the field
   */
  identifier?: string
}

export type GetAllSegmentsProps = Omit<
  GetProps<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAllSegmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all segments.
 *
 * Used to retrieve all segments for certain account id.
 */
export const GetAllSegments = (props: GetAllSegmentsProps) => (
  <Get<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAllSegmentsQueryParams,
    void
  >
    path={`/admin/segments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllSegmentsProps = Omit<
  UseGetProps<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAllSegmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all segments.
 *
 * Used to retrieve all segments for certain account id.
 */
export const useGetAllSegments = (props: UseGetAllSegmentsProps) =>
  useGet<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | InternalServerErrorResponse,
    GetAllSegmentsQueryParams,
    void
  >(`/admin/segments`, { base: getConfig('cf'), ...props })

export interface CreateSegmentQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type CreateSegmentProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateSegmentQueryParams,
    SegmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create segment.
 *
 * Used to create segment.
 */
export const CreateSegment = (props: CreateSegmentProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateSegmentQueryParams,
    SegmentRequestRequestBody,
    void
  >
    verb="POST"
    path={`/admin/segments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateSegmentProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateSegmentQueryParams,
    SegmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create segment.
 *
 * Used to create segment.
 */
export const useCreateSegment = (props: UseCreateSegmentProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateSegmentQueryParams,
    SegmentRequestRequestBody,
    void
  >('POST', `/admin/segments`, { base: getConfig('cf'), ...props })

export interface DeleteSegmentQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export type DeleteSegmentProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteSegmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete segment.
 *
 * Used to delete segment with certain id and account id.
 */
export const DeleteSegment = (props: DeleteSegmentProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteSegmentQueryParams,
    string,
    void
  >
    verb="DELETE"
    path={`/admin/segments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteSegmentProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteSegmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete segment.
 *
 * Used to delete segment with certain id and account id.
 */
export const useDeleteSegment = (props: UseDeleteSegmentProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteSegmentQueryParams,
    string,
    void
  >('DELETE', `/admin/segments`, { base: getConfig('cf'), ...props })

export interface GetSegmentQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface GetSegmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetSegmentProps = Omit<
  GetProps<
    SegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentQueryParams,
    GetSegmentPathParams
  >,
  'path'
> &
  GetSegmentPathParams

/**
 * Retrieve segment.
 *
 * Used to retrieve certain segment for certain id and account id.
 */
export const GetSegment = ({ identifier, ...props }: GetSegmentProps) => (
  <Get<
    SegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentQueryParams,
    GetSegmentPathParams
  >
    path={`/admin/segments/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetSegmentProps = Omit<
  UseGetProps<
    SegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentQueryParams,
    GetSegmentPathParams
  >,
  'path'
> &
  GetSegmentPathParams

/**
 * Retrieve segment.
 *
 * Used to retrieve certain segment for certain id and account id.
 */
export const useGetSegment = ({ identifier, ...props }: UseGetSegmentProps) =>
  useGet<
    SegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentQueryParams,
    GetSegmentPathParams
  >((paramsInPath: GetSegmentPathParams) => `/admin/segments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface PatchSegmentQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface PatchSegmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type PatchSegmentProps = Omit<
  MutateProps<
    SegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchSegmentQueryParams,
    SegmentPatchRequestRequestBody,
    PatchSegmentPathParams
  >,
  'path' | 'verb'
> &
  PatchSegmentPathParams

/**
 * Patch segment.
 *
 * Used to modify segment with certain id and account id.
 */
export const PatchSegment = ({ identifier, ...props }: PatchSegmentProps) => (
  <Mutate<
    SegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchSegmentQueryParams,
    SegmentPatchRequestRequestBody,
    PatchSegmentPathParams
  >
    verb="PATCH"
    path={`/admin/segments/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UsePatchSegmentProps = Omit<
  UseMutateProps<
    SegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchSegmentQueryParams,
    SegmentPatchRequestRequestBody,
    PatchSegmentPathParams
  >,
  'path' | 'verb'
> &
  PatchSegmentPathParams

/**
 * Patch segment.
 *
 * Used to modify segment with certain id and account id.
 */
export const usePatchSegment = ({ identifier, ...props }: UsePatchSegmentProps) =>
  useMutate<
    SegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchSegmentQueryParams,
    SegmentPatchRequestRequestBody,
    PatchSegmentPathParams
  >('PATCH', (paramsInPath: PatchSegmentPathParams) => `/admin/segments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetAvailableFlagsForSegmentQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: 'name'
  /**
   * Identifier of the feature flag
   */
  flagNameIdentifier?: string
}

export interface GetAvailableFlagsForSegmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetAvailableFlagsForSegmentProps = Omit<
  GetProps<
    AvailableFlagResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAvailableFlagsForSegmentQueryParams,
    GetAvailableFlagsForSegmentPathParams
  >,
  'path'
> &
  GetAvailableFlagsForSegmentPathParams

/**
 * Retrieve the available flags that the segment can be added to
 *
 * This returns the flags that the segment can be added to. This list will exclude any flags that the |
 *   segment currently belongs to.
 *
 */
export const GetAvailableFlagsForSegment = ({ identifier, ...props }: GetAvailableFlagsForSegmentProps) => (
  <Get<
    AvailableFlagResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAvailableFlagsForSegmentQueryParams,
    GetAvailableFlagsForSegmentPathParams
  >
    path={`/admin/segments/${identifier}/available_flags`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAvailableFlagsForSegmentProps = Omit<
  UseGetProps<
    AvailableFlagResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAvailableFlagsForSegmentQueryParams,
    GetAvailableFlagsForSegmentPathParams
  >,
  'path'
> &
  GetAvailableFlagsForSegmentPathParams

/**
 * Retrieve the available flags that the segment can be added to
 *
 * This returns the flags that the segment can be added to. This list will exclude any flags that the |
 *   segment currently belongs to.
 *
 */
export const useGetAvailableFlagsForSegment = ({ identifier, ...props }: UseGetAvailableFlagsForSegmentProps) =>
  useGet<
    AvailableFlagResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAvailableFlagsForSegmentQueryParams,
    GetAvailableFlagsForSegmentPathParams
  >(
    (paramsInPath: GetAvailableFlagsForSegmentPathParams) =>
      `/admin/segments/${paramsInPath.identifier}/available_flags`,
    { base: getConfig('cf'), pathParams: { identifier }, ...props }
  )

export interface GetSegmentFlagsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface GetSegmentFlagsPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetSegmentFlagsProps = Omit<
  GetProps<
    SegmentFlagsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentFlagsQueryParams,
    GetSegmentFlagsPathParams
  >,
  'path'
> &
  GetSegmentFlagsPathParams

/**
 * Retrieve segment flags.
 *
 * Used to retrieve certain segment flags for certain id and account id.
 */
export const GetSegmentFlags = ({ identifier, ...props }: GetSegmentFlagsProps) => (
  <Get<
    SegmentFlagsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentFlagsQueryParams,
    GetSegmentFlagsPathParams
  >
    path={`/admin/segments/${identifier}/flags`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetSegmentFlagsProps = Omit<
  UseGetProps<
    SegmentFlagsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentFlagsQueryParams,
    GetSegmentFlagsPathParams
  >,
  'path'
> &
  GetSegmentFlagsPathParams

/**
 * Retrieve segment flags.
 *
 * Used to retrieve certain segment flags for certain id and account id.
 */
export const useGetSegmentFlags = ({ identifier, ...props }: UseGetSegmentFlagsProps) =>
  useGet<
    SegmentFlagsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetSegmentFlagsQueryParams,
    GetSegmentFlagsPathParams
  >((paramsInPath: GetSegmentFlagsPathParams) => `/admin/segments/${paramsInPath.identifier}/flags`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetAllTargetsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * SortOrder
   */
  sortOrder?: 'ASC' | 'DESC'
  /**
   * SortByField
   */
  sortByField?: 'createdAt' | 'name' | 'identifier'
  /**
   * Name of the target
   */
  targetName?: string
  /**
   * Identifier of the target
   */
  targetIdentifier?: string
}

export type GetAllTargetsProps = Omit<
  GetProps<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all targets.
 *
 * Used to retrieve all targets for certain account id.
 */
export const GetAllTargets = (props: GetAllTargetsProps) => (
  <Get<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >
    path={`/admin/targets`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllTargetsProps = Omit<
  UseGetProps<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all targets.
 *
 * Used to retrieve all targets for certain account id.
 */
export const useGetAllTargets = (props: UseGetAllTargetsProps) =>
  useGet<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >(`/admin/targets`, { base: getConfig('cf'), ...props })

export interface CreateTargetQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
}

export type CreateTargetProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateTargetQueryParams,
    TargetRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create target.
 *
 * Used to create target.
 */
export const CreateTarget = (props: CreateTargetProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateTargetQueryParams,
    TargetRequestRequestBody,
    void
  >
    verb="POST"
    path={`/admin/targets`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateTargetProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateTargetQueryParams,
    TargetRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create target.
 *
 * Used to create target.
 */
export const useCreateTarget = (props: UseCreateTargetProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    CreateTargetQueryParams,
    TargetRequestRequestBody,
    void
  >('POST', `/admin/targets`, { base: getConfig('cf'), ...props })

export interface GetTargetsAndSegmentsInfoQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * Comma separated identifiers for multiple targets
   */
  targets?: string
  /**
   * Comma separated identifiers for multiple Target Groups
   */
  targetGroups?: string
}

export type GetTargetsAndSegmentsInfoProps = Omit<
  GetProps<
    TargetSegmentsInfoResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsInfoQueryParams,
    void
  >,
  'path'
>

/**
 * Get the name of specified targets and segments
 *
 * Get the names of the specified targets and segments
 */
export const GetTargetsAndSegmentsInfo = (props: GetTargetsAndSegmentsInfoProps) => (
  <Get<
    TargetSegmentsInfoResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsInfoQueryParams,
    void
  >
    path={`/admin/targets-segments-info/`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetTargetsAndSegmentsInfoProps = Omit<
  UseGetProps<
    TargetSegmentsInfoResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsInfoQueryParams,
    void
  >,
  'path'
>

/**
 * Get the name of specified targets and segments
 *
 * Get the names of the specified targets and segments
 */
export const useGetTargetsAndSegmentsInfo = (props: UseGetTargetsAndSegmentsInfoProps) =>
  useGet<
    TargetSegmentsInfoResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsInfoQueryParams,
    void
  >(`/admin/targets-segments-info/`, { base: getConfig('cf'), ...props })

export interface GetTargetsAndSegmentsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * Identifier of the target or segment
   */
  tsIdentifier?: string
  /**
   * Name of the target or segment
   */
  tsName?: string
  /**
   * SortByField
   */
  sortByField?: 'name' | 'identifier'
  /**
   * SortOrder
   */
  sortOrder?: 'ASC' | 'DESC'
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
}

export type GetTargetsAndSegmentsProps = Omit<
  GetProps<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Get targets and segments for an environment with search and sort features
 *
 * Get targets and segments for an environment with search and sort features
 */
export const GetTargetsAndSegments = (props: GetTargetsAndSegmentsProps) => (
  <Get<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsQueryParams,
    void
  >
    path={`/admin/targets-segments/`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetTargetsAndSegmentsProps = Omit<
  UseGetProps<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Get targets and segments for an environment with search and sort features
 *
 * Get targets and segments for an environment with search and sort features
 */
export const useGetTargetsAndSegments = (props: UseGetTargetsAndSegmentsProps) =>
  useGet<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetsAndSegmentsQueryParams,
    void
  >(`/admin/targets-segments/`, { base: getConfig('cf'), ...props })

export interface GetAllTargetAttributesQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export type GetAllTargetAttributesProps = Omit<
  GetProps<
    TargetAttributesResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetAttributesQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all target attributes for the environment
 *
 * Used to retrieve all attribute key names for all targets within the specified environment
 */
export const GetAllTargetAttributes = (props: GetAllTargetAttributesProps) => (
  <Get<
    TargetAttributesResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetAttributesQueryParams,
    void
  >
    path={`/admin/targets/attributes`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllTargetAttributesProps = Omit<
  UseGetProps<
    TargetAttributesResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetAttributesQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all target attributes for the environment
 *
 * Used to retrieve all attribute key names for all targets within the specified environment
 */
export const useGetAllTargetAttributes = (props: UseGetAllTargetAttributesProps) =>
  useGet<
    TargetAttributesResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetAttributesQueryParams,
    void
  >(`/admin/targets/attributes`, { base: getConfig('cf'), ...props })

export interface UploadTargetsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export type UploadTargetsProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UploadTargetsQueryParams,
    void,
    void
  >,
  'path' | 'verb'
>

/**
 * Upload targets
 *
 * Add targets by uploading a CSV file.
 */
export const UploadTargets = (props: UploadTargetsProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UploadTargetsQueryParams,
    void,
    void
  >
    verb="POST"
    path={`/admin/targets/upload`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseUploadTargetsProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UploadTargetsQueryParams,
    void,
    void
  >,
  'path' | 'verb'
>

/**
 * Upload targets
 *
 * Add targets by uploading a CSV file.
 */
export const useUploadTargets = (props: UseUploadTargetsProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    UploadTargetsQueryParams,
    void,
    void
  >('POST', `/admin/targets/upload`, { base: getConfig('cf'), ...props })

export interface DeleteTargetQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export type DeleteTargetProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete target.
 *
 * Used to delete target with certain id and account id.
 */
export const DeleteTarget = (props: DeleteTargetProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >
    verb="DELETE"
    path={`/admin/targets`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteTargetProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete target.
 *
 * Used to delete target with certain id and account id.
 */
export const useDeleteTarget = (props: UseDeleteTargetProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >('DELETE', `/admin/targets`, { base: getConfig('cf'), ...props })

export interface GetTargetQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface GetTargetPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetTargetProps = Omit<
  GetProps<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >,
  'path'
> &
  GetTargetPathParams

/**
 * Retrieve target.
 *
 * Used to retrieve certain target for certain id and account id.
 */
export const GetTarget = ({ identifier, ...props }: GetTargetProps) => (
  <Get<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >
    path={`/admin/targets/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetTargetProps = Omit<
  UseGetProps<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >,
  'path'
> &
  GetTargetPathParams

/**
 * Retrieve target.
 *
 * Used to retrieve certain target for certain id and account id.
 */
export const useGetTarget = ({ identifier, ...props }: UseGetTargetProps) =>
  useGet<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >((paramsInPath: GetTargetPathParams) => `/admin/targets/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface PatchTargetQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface PatchTargetPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type PatchTargetProps = Omit<
  MutateProps<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetQueryParams,
    TargetPatchRequestRequestBody,
    PatchTargetPathParams
  >,
  'path' | 'verb'
> &
  PatchTargetPathParams

/**
 * Patch target.
 *
 * Used to modify target with certain id and account id.
 */
export const PatchTarget = ({ identifier, ...props }: PatchTargetProps) => (
  <Mutate<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetQueryParams,
    TargetPatchRequestRequestBody,
    PatchTargetPathParams
  >
    verb="PATCH"
    path={`/admin/targets/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UsePatchTargetProps = Omit<
  UseMutateProps<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetQueryParams,
    TargetPatchRequestRequestBody,
    PatchTargetPathParams
  >,
  'path' | 'verb'
> &
  PatchTargetPathParams

/**
 * Patch target.
 *
 * Used to modify target with certain id and account id.
 */
export const usePatchTarget = ({ identifier, ...props }: UsePatchTargetProps) =>
  useMutate<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetQueryParams,
    TargetPatchRequestRequestBody,
    PatchTargetPathParams
  >('PATCH', (paramsInPath: PatchTargetPathParams) => `/admin/targets/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface ModifyTargetQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface ModifyTargetPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type ModifyTargetProps = Omit<
  MutateProps<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >,
  'path' | 'verb'
> &
  ModifyTargetPathParams

/**
 * Modify target
 *
 * Used to modify target with certain id and account id.
 */
export const ModifyTarget = ({ identifier, ...props }: ModifyTargetProps) => (
  <Mutate<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >
    verb="PUT"
    path={`/admin/targets/${identifier}`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseModifyTargetProps = Omit<
  UseMutateProps<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >,
  'path' | 'verb'
> &
  ModifyTargetPathParams

/**
 * Modify target
 *
 * Used to modify target with certain id and account id.
 */
export const useModifyTarget = ({ identifier, ...props }: UseModifyTargetProps) =>
  useMutate<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >('PUT', (paramsInPath: ModifyTargetPathParams) => `/admin/targets/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface GetTargetAvailableSegmentsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: 'name'
  /**
   * Name of the segment
   */
  segmentName?: string
}

export interface GetTargetAvailableSegmentsPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetTargetAvailableSegmentsProps = Omit<
  GetProps<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetAvailableSegmentsQueryParams,
    GetTargetAvailableSegmentsPathParams
  >,
  'path'
> &
  GetTargetAvailableSegmentsPathParams

/**
 * Retrieve the available segments that the target can be included in or excluded from.
 *
 * This returns the segments that the target can be added to. This list will exclude any segments that the |
 *   target currently belongs to.
 *
 */
export const GetTargetAvailableSegments = ({ identifier, ...props }: GetTargetAvailableSegmentsProps) => (
  <Get<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetAvailableSegmentsQueryParams,
    GetTargetAvailableSegmentsPathParams
  >
    path={`/admin/targets/${identifier}/available_segments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetTargetAvailableSegmentsProps = Omit<
  UseGetProps<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetAvailableSegmentsQueryParams,
    GetTargetAvailableSegmentsPathParams
  >,
  'path'
> &
  GetTargetAvailableSegmentsPathParams

/**
 * Retrieve the available segments that the target can be included in or excluded from.
 *
 * This returns the segments that the target can be added to. This list will exclude any segments that the |
 *   target currently belongs to.
 *
 */
export const useGetTargetAvailableSegments = ({ identifier, ...props }: UseGetTargetAvailableSegmentsProps) =>
  useGet<
    SegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetAvailableSegmentsQueryParams,
    GetTargetAvailableSegmentsPathParams
  >(
    (paramsInPath: GetTargetAvailableSegmentsPathParams) =>
      `/admin/targets/${paramsInPath.identifier}/available_segments`,
    { base: getConfig('cf'), pathParams: { identifier }, ...props }
  )

export interface GetTargetSegmentsQueryParams {
  /**
   * Account
   */
  accountIdentifier: string
  /**
   * Organization Identifier
   */
  org: string
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface GetTargetSegmentsPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetTargetSegmentsProps = Omit<
  GetProps<
    TargetDetailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentsQueryParams,
    GetTargetSegmentsPathParams
  >,
  'path'
> &
  GetTargetSegmentsPathParams

/**
 * Retrieve the segmenets that the specified target belongs to.
 *
 * Used to retrieve certain segments for a certian target
 */
export const GetTargetSegments = ({ identifier, ...props }: GetTargetSegmentsProps) => (
  <Get<
    TargetDetailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentsQueryParams,
    GetTargetSegmentsPathParams
  >
    path={`/admin/targets/${identifier}/segments`}
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetTargetSegmentsProps = Omit<
  UseGetProps<
    TargetDetailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentsQueryParams,
    GetTargetSegmentsPathParams
  >,
  'path'
> &
  GetTargetSegmentsPathParams

/**
 * Retrieve the segmenets that the specified target belongs to.
 *
 * Used to retrieve certain segments for a certian target
 */
export const useGetTargetSegments = ({ identifier, ...props }: UseGetTargetSegmentsProps) =>
  useGet<
    TargetDetailResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentsQueryParams,
    GetTargetSegmentsPathParams
  >((paramsInPath: GetTargetSegmentsPathParams) => `/admin/targets/${paramsInPath.identifier}/segments`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })
