/* Generated by restful-react */

import React from 'react'
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react'

import { getConfig } from '../config'
export interface HealthResponse {
  healthy?: boolean
}

export type Status = 'SUCCESS' | 'FAILURE' | 'ERROR'

/**
 * A name and value pair.
 */
export interface Tag {
  name: string
  value?: string
}

export interface Project {
  name: string
  description?: string
  identifier: string
  tags?: Tag[]
}

export interface Projects {
  pageCount?: number
  itemCount?: number
  pageSize?: number
  pageIndex?: number
  projects?: Project[]
}

export interface Error {
  code: string
  message: string
}

export interface ApiKey {
  name: string
  apiKey: string
  identifier: string
}

export type ApiKeys = ApiKey[]

export interface Environment {
  name: string
  description?: string
  identifier?: string
  project?: string
  apiKeys?: ApiKeys
  tags?: Tag[]
}

export interface Environments {
  environments?: Environment[]
}

export interface Pagination {
  version?: number
  pageCount: number
  itemCount: number
  pageSize: number
  pageIndex: number
}

export interface Prerequisite {
  feature: string
  variations: string[]
}

export interface Variation {
  identifier: string
  value: string
  name?: string
  description?: string
}

export interface VariationMap {
  variation: string
  targets?: string[]
  targetSegments?: string[]
}

export interface Clause {
  id: string
  attribute?: string
  op: string
  value: string[]
  negate: boolean
}

export interface WeightedVariation {
  variation: string
  weight: number
}

export interface Distribution {
  bucketBy: string
  variations: WeightedVariation[]
}

export interface Serve {
  distribution?: Distribution
  variation?: string
}

export interface ServingRule {
  ruleId: string
  priority: number
  clauses: Clause[]
  serve: Serve
}

export type FeatureState = 'on' | 'off'

export interface Feature {
  project: string
  identifier: string
  prerequisites?: Prerequisite[]
  name: string
  description?: string
  owner?: string[]
  kind: 'boolean' | 'int' | 'string' | 'json'
  archived: boolean
  variations: Variation[]
  defaultOnVariation: string
  defaultOffVariation: string
  permanent: boolean
  envProperties?: {
    environment: string
    variationMap?: VariationMap[]
    rules?: ServingRule[]
    state: FeatureState
    defaultServe: Serve
    offVariation: string
    createdAt: number
    modifiedAt: number
    version?: number
  }
  createdAt: number
  modifiedAt: number
  tags?: Tag[]
  version?: any
}

export type Features = Pagination & {
  features?: Feature[]
}

export type PatchInstruction = {
  /**
   * The name of the modification you would like to perform on a resource.
   */
  kind: string
  parameters: { [key: string]: any }
}[]

export interface PatchOperation {
  comment?: string
  /**
   * Time of execution in unix epoch milliseconds when the scheduled changes will be applied
   */
  executionTime?: number
  instructions: PatchInstruction
}

export interface Target {
  Anonymous?: boolean
  Attributes?: { [key: string]: any }
  CreatedAt: string
  DeletedAt: string | null
  Environment: string
  EnvironmentID: string
  ID: string
  Identifier: string
  Name: string
  Project: string
  ProjectID: string
  UpdatedAt: string
}

export interface Targets {
  pageCount?: number
  itemCount?: number
  pageSize?: number
  pageIndex?: number
  targets?: Target[]
}

export interface TargetSegment {
  /**
   * Unique identifier for the target segment.
   */
  identifier: string
  /**
   * Name of the target segment.
   */
  name: string
  environment?: string
  tags?: Tag[]
  included?: string[]
  excluded?: string[]
  /**
   * An array of rules that can cause a user to be included in this segment.
   */
  rules?: Clause[]
  createdAt?: number
  modifiedAt?: number
  version?: number
}

export interface TargetSegments {
  pageCount?: number
  itemCount?: number
  pageSize?: number
  pageIndex?: number
  targetsegments?: TargetSegment[]
}

export interface ProjectRequestRequestBody {
  identifier: string
  name: string
  description?: string
  tags?: Tag[]
}

export interface APIKeyRequestRequestBody {
  identifier: string
  name: string
  environment: string
  project: string
}

export interface EnvironmentRequestRequestBody {
  identifier: string
  name: string
  description?: string
  project: string
  tags?: Tag[]
}

export type FeatureFlagRequestRequestBody = {
  project: string
  prerequisites?: Prerequisite[]
  name: string
  description?: string
  identifier: string
  owner?: string
  kind: 'boolean' | 'int' | 'string' | 'json'
  archived?: boolean
  variations: Variation[]
  tags?: Tag[]
  defaultOnVariation?: string
  defaultOffVariation?: string
  permanent?: boolean
}

export type FeatureFlagPatchRequestRequestBody = PatchOperation

export type TargetRequestRequestBody = Target

export interface TargetSegmentRequestRequestBody {
  identifier?: string
  /**
   * Name of the target segment.
   */
  name: string
  environment: string
  project: string
  tags?: Tag[]
  included?: string[]
  excluded?: string[]
  /**
   * An array of rules that can cause a user to be included in this segment.
   */
  rules?: Clause[]
}

export type TargetSegmentPatchRequestRequestBody = PatchOperation

/**
 * OK
 */
export interface ProjectsResponseResponse {
  status?: Status
  data?: Projects
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * Unauthenticated
 */
export type UnauthenticatedResponse = Error

/**
 * Unauthorized
 */
export type UnauthorizedResponse = Error

/**
 * The specified resource was not found
 */
export type NotFoundResponse = Error

/**
 * Internal server error
 */
export type InternalServerErrorResponse = Error

/**
 * Bad request
 */
export type BadRequestResponse = Error

/**
 * The specified resource already exists
 */
export type ConflictResponse = Error

/**
 * OK
 */
export interface ProjectResponseResponse {
  status?: Status
  data?: Project
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * OK
 */
export interface EnvironmentsResponseResponse {
  status: Status
  data: Environments
  metaData?: { [key: string]: any }
  correlationId: string
}

/**
 * OK
 */
export interface EnvironmentResponseResponse {
  status?: Status
  data?: Environment
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * OK
 */
export interface FeaturesResponseResponse {
  status?: Status
  data?: Features
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * OK
 */
export interface FeatureResponseResponse {
  status?: Status
  data?: Feature
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * OK
 */
export interface TargetsResponseResponse {
  status?: Status
  data?: Targets
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * OK
 */
export interface TargetResponseResponse {
  status?: Status
  data?: Target
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * OK
 */
export interface TargetSegmentsResponseResponse {
  status?: Status
  data?: TargetSegments
  metaData?: { [key: string]: any }
  correlationId?: string
}

/**
 * OK
 */
export interface TargetSegmentResponseResponse {
  status?: Status
  data?: TargetSegment
  metaData?: { [key: string]: any }
  correlationId?: string
}

export type GetHealthStatusProps = Omit<GetProps<HealthResponse, void, void, void>, 'path'>

/**
 * Request basic health status.
 */
export const GetHealthStatus = (props: GetHealthStatusProps) => (
  <Get<HealthResponse, void, void, void> path="/health" base={getConfig('cf')} {...props} />
)

export type UseGetHealthStatusProps = Omit<UseGetProps<HealthResponse, void, void, void>, 'path'>

/**
 * Request basic health status.
 */
export const useGetHealthStatus = (props: UseGetHealthStatusProps) =>
  useGet<HealthResponse, void, void, void>(`/health`, { base: getConfig('cf'), ...props })

export type CreateProjectProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Project.
 *
 * Used to create a project.
 */
export const CreateProject = (props: CreateProjectProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    void
  >
    verb="POST"
    path="/admin/projects"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateProjectProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Project.
 *
 * Used to create a project.
 */
export const useCreateProject = (props: UseCreateProjectProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    void
  >('POST', `/admin/projects`, { base: getConfig('cf'), ...props })

export interface GetAllProjectsQueryParams {
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * query
   */
  queryString?: string
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: string
}

export type GetAllProjectsProps = Omit<
  GetProps<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all projects
 *
 * Get all projects
 */
export const GetAllProjects = (props: GetAllProjectsProps) => (
  <Get<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >
    path="/admin/projects"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllProjectsProps = Omit<
  UseGetProps<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all projects
 *
 * Get all projects
 */
export const useGetAllProjects = (props: UseGetAllProjectsProps) =>
  useGet<
    ProjectsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllProjectsQueryParams,
    void
  >(`/admin/projects`, { base: getConfig('cf'), ...props })

export interface GetProjectPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetProjectProps = Omit<
  GetProps<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetProjectPathParams
  >,
  'path'
> &
  GetProjectPathParams

/**
 * Get Project by an key.
 *
 * Used to retrieve project by the projectKey.
 */
export const GetProject = ({ identifier, ...props }: GetProjectProps) => (
  <Get<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetProjectPathParams
  >
    path="/admin/projects/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetProjectProps = Omit<
  UseGetProps<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetProjectPathParams
  >,
  'path'
> &
  GetProjectPathParams

/**
 * Get Project by an key.
 *
 * Used to retrieve project by the projectKey.
 */
export const useGetProject = ({ identifier, ...props }: UseGetProjectProps) =>
  useGet<
    ProjectResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    GetProjectPathParams
  >((paramsInPath: GetProjectPathParams) => `/admin/projects/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface ModifyProjectPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type ModifyProjectProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >,
  'path' | 'verb'
> &
  ModifyProjectPathParams

/**
 * Modify a Project.
 *
 * Used to modify a project.
 */
export const ModifyProject = ({ identifier, ...props }: ModifyProjectProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >
    verb="PUT"
    path="/admin/projects/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseModifyProjectProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >,
  'path' | 'verb'
> &
  ModifyProjectPathParams

/**
 * Modify a Project.
 *
 * Used to modify a project.
 */
export const useModifyProject = ({ identifier, ...props }: UseModifyProjectProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    ProjectRequestRequestBody,
    ModifyProjectPathParams
  >('PUT', (paramsInPath: ModifyProjectPathParams) => `/admin/projects/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export type DeleteProjectProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Project
 *
 * Used to delete project
 */
export const DeleteProject = (props: DeleteProjectProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    string,
    void
  >
    verb="DELETE"
    path="/admin/projects"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteProjectProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Project
 *
 * Used to delete project
 */
export const useDeleteProject = (props: UseDeleteProjectProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    void,
    string,
    void
  >('DELETE', `/admin/projects`, { base: getConfig('cf'), ...props })

export type AddAPIKeyProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    APIKeyRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Add an API Key to environment.
 *
 * Used to create a key in an environment.
 */
export const AddAPIKey = (props: AddAPIKeyProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    APIKeyRequestRequestBody,
    void
  >
    verb="POST"
    path="/admin/apikey"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseAddAPIKeyProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    APIKeyRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Add an API Key to environment.
 *
 * Used to create a key in an environment.
 */
export const useAddAPIKey = (props: UseAddAPIKeyProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    APIKeyRequestRequestBody,
    void
  >('POST', `/admin/apikey`, { base: getConfig('cf'), ...props })

export interface DeleteApiKeyQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export type DeleteApiKeyProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete APIKey
 *
 * Used to delete an APIKey
 */
export const DeleteApiKey = (props: DeleteApiKeyProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >
    verb="DELETE"
    path="/admin/apikey"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteApiKeyProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete APIKey
 *
 * Used to delete an APIKey
 */
export const useDeleteApiKey = (props: UseDeleteApiKeyProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteApiKeyQueryParams,
    string,
    void
  >('DELETE', `/admin/apikey`, { base: getConfig('cf'), ...props })

export type CreateEnvironmentProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    EnvironmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Environment.
 *
 * Used to create an environment.
 */
export const CreateEnvironment = (props: CreateEnvironmentProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    EnvironmentRequestRequestBody,
    void
  >
    verb="POST"
    path="/admin/environments"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateEnvironmentProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    EnvironmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create Environment.
 *
 * Used to create an environment.
 */
export const useCreateEnvironment = (props: UseCreateEnvironmentProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    EnvironmentRequestRequestBody,
    void
  >('POST', `/admin/environments`, { base: getConfig('cf'), ...props })

export interface GetAllEnvironmentsQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * query
   */
  queryString?: string
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: string
}

export type GetAllEnvironmentsProps = Omit<
  GetProps<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all environments in a project
 *
 * Get all the environments in a project
 */
export const GetAllEnvironments = (props: GetAllEnvironmentsProps) => (
  <Get<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >
    path="/admin/environments"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllEnvironmentsProps = Omit<
  UseGetProps<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Get all environments in a project
 *
 * Get all the environments in a project
 */
export const useGetAllEnvironments = (props: UseGetAllEnvironmentsProps) =>
  useGet<
    EnvironmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllEnvironmentsQueryParams,
    void
  >(`/admin/environments`, { base: getConfig('cf'), ...props })

export interface GetEnvironmentQueryParams {
  /**
   * Project
   */
  project: string
}

export interface GetEnvironmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetEnvironmentProps = Omit<
  GetProps<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >,
  'path'
> &
  GetEnvironmentPathParams

/**
 * Get Environment by an identifier.
 *
 * Used to retrieve an Environment by the Environment Identifier.
 */
export const GetEnvironment = ({ identifier, ...props }: GetEnvironmentProps) => (
  <Get<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >
    path="/admin/environments/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetEnvironmentProps = Omit<
  UseGetProps<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >,
  'path'
> &
  GetEnvironmentPathParams

/**
 * Get Environment by an identifier.
 *
 * Used to retrieve an Environment by the Environment Identifier.
 */
export const useGetEnvironment = ({ identifier, ...props }: UseGetEnvironmentProps) =>
  useGet<
    EnvironmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetEnvironmentQueryParams,
    GetEnvironmentPathParams
  >((paramsInPath: GetEnvironmentPathParams) => `/admin/environments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface ModifyEnvironmentQueryParams {
  /**
   * Project
   */
  project: string
}

export interface ModifyEnvironmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type ModifyEnvironmentProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >,
  'path' | 'verb'
> &
  ModifyEnvironmentPathParams

/**
 * Modify an Environment.
 *
 * Used to modify an Environment.
 */
export const ModifyEnvironment = ({ identifier, ...props }: ModifyEnvironmentProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >
    verb="PUT"
    path="/admin/environments/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseModifyEnvironmentProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >,
  'path' | 'verb'
> &
  ModifyEnvironmentPathParams

/**
 * Modify an Environment.
 *
 * Used to modify an Environment.
 */
export const useModifyEnvironment = ({ identifier, ...props }: UseModifyEnvironmentProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyEnvironmentQueryParams,
    EnvironmentRequestRequestBody,
    ModifyEnvironmentPathParams
  >('PUT', (paramsInPath: ModifyEnvironmentPathParams) => `/admin/environments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface DeleteEnvironmentQueryParams {
  /**
   * Project
   */
  project: string
}

export type DeleteEnvironmentProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Environment
 *
 * Used to delete an Environment
 */
export const DeleteEnvironment = (props: DeleteEnvironmentProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >
    verb="DELETE"
    path="/admin/environments"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteEnvironmentProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete Environment
 *
 * Used to delete an Environment
 */
export const useDeleteEnvironment = (props: UseDeleteEnvironmentProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteEnvironmentQueryParams,
    string,
    void
  >('DELETE', `/admin/environments`, { base: getConfig('cf'), ...props })

export interface StreamPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type StreamProps = Omit<GetProps<void, void, void, StreamPathParams>, 'path'> & StreamPathParams

/**
 * Stream endpoint.
 */
export const Stream = ({ identifier, ...props }: StreamProps) => (
  <Get<void, void, void, StreamPathParams>
    path="/stream/environments/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseStreamProps = Omit<UseGetProps<void, void, void, StreamPathParams>, 'path'> & StreamPathParams

/**
 * Stream endpoint.
 */
export const useStream = ({ identifier, ...props }: UseStreamProps) =>
  useGet<void, void, void, StreamPathParams>(
    (paramsInPath: StreamPathParams) => `/stream/environments/${paramsInPath.identifier}`,
    { base: getConfig('cf'), pathParams: { identifier }, ...props }
  )

export type CreateFeatureFlagProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    FeatureFlagRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create feature flag.
 *
 * Used to create feature flag.
 */
export const CreateFeatureFlag = (props: CreateFeatureFlagProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    FeatureFlagRequestRequestBody,
    void
  >
    verb="POST"
    path="/admin/features"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateFeatureFlagProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    FeatureFlagRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create feature flag.
 *
 * Used to create feature flag.
 */
export const useCreateFeatureFlag = (props: UseCreateFeatureFlagProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    FeatureFlagRequestRequestBody,
    void
  >('POST', `/admin/features`, { base: getConfig('cf'), ...props })

export interface GetAllFeaturesQueryParams {
  /**
   * Environment
   */
  environment: string
  /**
   * Project
   */
  project: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * query
   */
  queryString?: string
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: string
}

export type GetAllFeaturesProps = Omit<
  GetProps<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all feature activations.
 *
 * Used to retrieve all feature activations for certain account id.
 */
export const GetAllFeatures = (props: GetAllFeaturesProps) => (
  <Get<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >
    path="/admin/features"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllFeaturesProps = Omit<
  UseGetProps<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all feature activations.
 *
 * Used to retrieve all feature activations for certain account id.
 */
export const useGetAllFeatures = (props: UseGetAllFeaturesProps) =>
  useGet<
    FeaturesResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllFeaturesQueryParams,
    void
  >(`/admin/features`, { base: getConfig('cf'), ...props })

export interface GetFeatureFlagQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface GetFeatureFlagPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetFeatureFlagProps = Omit<
  GetProps<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >,
  'path'
> &
  GetFeatureFlagPathParams

/**
 * Retrieve feature flag.
 *
 * Used to retrieve certain feature flags for certain id and account id.
 */
export const GetFeatureFlag = ({ identifier, ...props }: GetFeatureFlagProps) => (
  <Get<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >
    path="/admin/features/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetFeatureFlagProps = Omit<
  UseGetProps<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >,
  'path'
> &
  GetFeatureFlagPathParams

/**
 * Retrieve feature flag.
 *
 * Used to retrieve certain feature flags for certain id and account id.
 */
export const useGetFeatureFlag = ({ identifier, ...props }: UseGetFeatureFlagProps) =>
  useGet<
    FeatureResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetFeatureFlagQueryParams,
    GetFeatureFlagPathParams
  >((paramsInPath: GetFeatureFlagPathParams) => `/admin/features/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface PatchFeatureFlagQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface PatchFeatureFlagPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type PatchFeatureFlagProps = Omit<
  MutateProps<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureFlagQueryParams,
    FeatureFlagPatchRequestRequestBody,
    PatchFeatureFlagPathParams
  >,
  'path' | 'verb'
> &
  PatchFeatureFlagPathParams

/**
 * Modify feature flag using instructions.
 *
 * Used to modify feature flag with certain id and account id.
 */
export const PatchFeatureFlag = ({ identifier, ...props }: PatchFeatureFlagProps) => (
  <Mutate<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureFlagQueryParams,
    FeatureFlagPatchRequestRequestBody,
    PatchFeatureFlagPathParams
  >
    verb="PATCH"
    path="/admin/features/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UsePatchFeatureFlagProps = Omit<
  UseMutateProps<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureFlagQueryParams,
    FeatureFlagPatchRequestRequestBody,
    PatchFeatureFlagPathParams
  >,
  'path' | 'verb'
> &
  PatchFeatureFlagPathParams

/**
 * Modify feature flag using instructions.
 *
 * Used to modify feature flag with certain id and account id.
 */
export const usePatchFeatureFlag = ({ identifier, ...props }: UsePatchFeatureFlagProps) =>
  useMutate<
    FeatureResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchFeatureFlagQueryParams,
    FeatureFlagPatchRequestRequestBody,
    PatchFeatureFlagPathParams
  >('PATCH', (paramsInPath: PatchFeatureFlagPathParams) => `/admin/features/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface DeleteFeatureFlagQueryParams {
  /**
   * Project
   */
  project: string
}

export type DeleteFeatureFlagProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete feature flag.
 *
 * Used to delete feature flag with certain id and account id.
 */
export const DeleteFeatureFlag = (props: DeleteFeatureFlagProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >
    verb="DELETE"
    path="/admin/features"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteFeatureFlagProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete feature flag.
 *
 * Used to delete feature flag with certain id and account id.
 */
export const useDeleteFeatureFlag = (props: UseDeleteFeatureFlagProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteFeatureFlagQueryParams,
    string,
    void
  >('DELETE', `/admin/features`, { base: getConfig('cf'), ...props })

export type CreateTargetProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create target.
 *
 * Used to create target.
 */
export const CreateTarget = (props: CreateTargetProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetRequestRequestBody,
    void
  >
    verb="POST"
    path="/admin/targets"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateTargetProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create target.
 *
 * Used to create target.
 */
export const useCreateTarget = (props: UseCreateTargetProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetRequestRequestBody,
    void
  >('POST', `/admin/targets`, { base: getConfig('cf'), ...props })

export interface GetAllTargetsQueryParams {
  /**
   * Environment
   */
  environment: string
  /**
   * Project
   */
  project: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * query
   */
  queryString?: string
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: string
}

export type GetAllTargetsProps = Omit<
  GetProps<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all targets.
 *
 * Used to retrieve all targets for certain account id.
 */
export const GetAllTargets = (props: GetAllTargetsProps) => (
  <Get<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >
    path="/admin/targets"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllTargetsProps = Omit<
  UseGetProps<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all targets.
 *
 * Used to retrieve all targets for certain account id.
 */
export const useGetAllTargets = (props: UseGetAllTargetsProps) =>
  useGet<
    TargetsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetsQueryParams,
    void
  >(`/admin/targets`, { base: getConfig('cf'), ...props })

export interface GetTargetQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface GetTargetPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetTargetProps = Omit<
  GetProps<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >,
  'path'
> &
  GetTargetPathParams

/**
 * Retrieve target.
 *
 * Used to retrieve certain target for certain id and account id.
 */
export const GetTarget = ({ identifier, ...props }: GetTargetProps) => (
  <Get<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >
    path="/admin/targets/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetTargetProps = Omit<
  UseGetProps<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >,
  'path'
> &
  GetTargetPathParams

/**
 * Retrieve target.
 *
 * Used to retrieve certain target for certain id and account id.
 */
export const useGetTarget = ({ identifier, ...props }: UseGetTargetProps) =>
  useGet<
    TargetResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetQueryParams,
    GetTargetPathParams
  >((paramsInPath: GetTargetPathParams) => `/admin/targets/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface ModifyTargetQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface ModifyTargetPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type ModifyTargetProps = Omit<
  MutateProps<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >,
  'path' | 'verb'
> &
  ModifyTargetPathParams

/**
 * Modify target.
 *
 * Used to modify target with certain id and account id.
 */
export const ModifyTarget = ({ identifier, ...props }: ModifyTargetProps) => (
  <Mutate<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >
    verb="PUT"
    path="/admin/targets/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseModifyTargetProps = Omit<
  UseMutateProps<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >,
  'path' | 'verb'
> &
  ModifyTargetPathParams

/**
 * Modify target.
 *
 * Used to modify target with certain id and account id.
 */
export const useModifyTarget = ({ identifier, ...props }: UseModifyTargetProps) =>
  useMutate<
    TargetResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    ModifyTargetQueryParams,
    TargetRequestRequestBody,
    ModifyTargetPathParams
  >('PUT', (paramsInPath: ModifyTargetPathParams) => `/admin/targets/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface DeleteTargetQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export type DeleteTargetProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete target.
 *
 * Used to delete target with certain id and account id.
 */
export const DeleteTarget = (props: DeleteTargetProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >
    verb="DELETE"
    path="/admin/targets"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteTargetProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete target.
 *
 * Used to delete target with certain id and account id.
 */
export const useDeleteTarget = (props: UseDeleteTargetProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetQueryParams,
    string,
    void
  >('DELETE', `/admin/targets`, { base: getConfig('cf'), ...props })

export type CreateTargetSegmentProps = Omit<
  MutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetSegmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create target segment.
 *
 * Used to create target segment.
 */
export const CreateTargetSegment = (props: CreateTargetSegmentProps) => (
  <Mutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetSegmentRequestRequestBody,
    void
  >
    verb="POST"
    path="/admin/target-segments"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseCreateTargetSegmentProps = Omit<
  UseMutateProps<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetSegmentRequestRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Create target segment.
 *
 * Used to create target segment.
 */
export const useCreateTargetSegment = (props: UseCreateTargetSegmentProps) =>
  useMutate<
    void,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    void,
    TargetSegmentRequestRequestBody,
    void
  >('POST', `/admin/target-segments`, { base: getConfig('cf'), ...props })

export interface GetAllTargetSegmentsQueryParams {
  /**
   * Environment
   */
  environment: string
  /**
   * Project
   */
  project: string
  /**
   * PageNumber
   */
  pageNumber?: number
  /**
   * PageSize
   */
  pageSize?: number
  /**
   * query
   */
  queryString?: string
  /**
   * SortOrder
   */
  sortOrder?: 'ASCENDING' | 'DESCENDING'
  /**
   * SortByField
   */
  sortByField?: string
}

export type GetAllTargetSegmentsProps = Omit<
  GetProps<
    TargetSegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetSegmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all target segments.
 *
 * Used to retrieve all target segments for certain account id.
 */
export const GetAllTargetSegments = (props: GetAllTargetSegmentsProps) => (
  <Get<
    TargetSegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetSegmentsQueryParams,
    void
  >
    path="/admin/target-segments"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetAllTargetSegmentsProps = Omit<
  UseGetProps<
    TargetSegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetSegmentsQueryParams,
    void
  >,
  'path'
>

/**
 * Retrieve all target segments.
 *
 * Used to retrieve all target segments for certain account id.
 */
export const useGetAllTargetSegments = (props: UseGetAllTargetSegmentsProps) =>
  useGet<
    TargetSegmentsResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetAllTargetSegmentsQueryParams,
    void
  >(`/admin/target-segments`, { base: getConfig('cf'), ...props })

export interface GetTargetSegmentQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface GetTargetSegmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type GetTargetSegmentProps = Omit<
  GetProps<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentQueryParams,
    GetTargetSegmentPathParams
  >,
  'path'
> &
  GetTargetSegmentPathParams

/**
 * Retrieve target segment.
 *
 * Used to retrieve certain target segment for certain id and account id.
 */
export const GetTargetSegment = ({ identifier, ...props }: GetTargetSegmentProps) => (
  <Get<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentQueryParams,
    GetTargetSegmentPathParams
  >
    path="/admin/target-segments/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseGetTargetSegmentProps = Omit<
  UseGetProps<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentQueryParams,
    GetTargetSegmentPathParams
  >,
  'path'
> &
  GetTargetSegmentPathParams

/**
 * Retrieve target segment.
 *
 * Used to retrieve certain target segment for certain id and account id.
 */
export const useGetTargetSegment = ({ identifier, ...props }: UseGetTargetSegmentProps) =>
  useGet<
    TargetSegmentResponseResponse,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    GetTargetSegmentQueryParams,
    GetTargetSegmentPathParams
  >((paramsInPath: GetTargetSegmentPathParams) => `/admin/target-segments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface PatchTargetSegmentQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export interface PatchTargetSegmentPathParams {
  /**
   * Unique identifier for the object in the API.
   */
  identifier: string
}

export type PatchTargetSegmentProps = Omit<
  MutateProps<
    TargetSegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetSegmentQueryParams,
    TargetSegmentPatchRequestRequestBody,
    PatchTargetSegmentPathParams
  >,
  'path' | 'verb'
> &
  PatchTargetSegmentPathParams

/**
 * Patch target segment.
 *
 * Used to modify target segment with certain id and account id.
 */
export const PatchTargetSegment = ({ identifier, ...props }: PatchTargetSegmentProps) => (
  <Mutate<
    TargetSegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetSegmentQueryParams,
    TargetSegmentPatchRequestRequestBody,
    PatchTargetSegmentPathParams
  >
    verb="PATCH"
    path="/admin/target-segments/${identifier}"
    base={getConfig('cf')}
    {...props}
  />
)

export type UsePatchTargetSegmentProps = Omit<
  UseMutateProps<
    TargetSegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetSegmentQueryParams,
    TargetSegmentPatchRequestRequestBody,
    PatchTargetSegmentPathParams
  >,
  'path' | 'verb'
> &
  PatchTargetSegmentPathParams

/**
 * Patch target segment.
 *
 * Used to modify target segment with certain id and account id.
 */
export const usePatchTargetSegment = ({ identifier, ...props }: UsePatchTargetSegmentProps) =>
  useMutate<
    TargetSegmentResponseResponse,
    | BadRequestResponse
    | UnauthenticatedResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | ConflictResponse
    | InternalServerErrorResponse,
    PatchTargetSegmentQueryParams,
    TargetSegmentPatchRequestRequestBody,
    PatchTargetSegmentPathParams
  >('PATCH', (paramsInPath: PatchTargetSegmentPathParams) => `/admin/target-segments/${paramsInPath.identifier}`, {
    base: getConfig('cf'),
    pathParams: { identifier },
    ...props
  })

export interface DeleteTargetSegmentQueryParams {
  /**
   * Project
   */
  project: string
  /**
   * Environment
   */
  environment: string
}

export type DeleteTargetSegmentProps = Omit<
  MutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetSegmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete target segment.
 *
 * Used to delete target segment with certain id and account id.
 */
export const DeleteTargetSegment = (props: DeleteTargetSegmentProps) => (
  <Mutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetSegmentQueryParams,
    string,
    void
  >
    verb="DELETE"
    path="/admin/target-segments"
    base={getConfig('cf')}
    {...props}
  />
)

export type UseDeleteTargetSegmentProps = Omit<
  UseMutateProps<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetSegmentQueryParams,
    string,
    void
  >,
  'path' | 'verb'
>

/**
 * Delete target segment.
 *
 * Used to delete target segment with certain id and account id.
 */
export const useDeleteTargetSegment = (props: UseDeleteTargetSegmentProps) =>
  useMutate<
    void,
    UnauthenticatedResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    DeleteTargetSegmentQueryParams,
    string,
    void
  >('DELETE', `/admin/target-segments`, { base: getConfig('cf'), ...props })
