#! /usr/bin/env node
const fs = require('fs')
const path = require('path')

;(async () => {
  const modules = path.resolve(__dirname, '../src/modules')

  const dirs = await fs.promises.readdir(modules, { withFileTypes: true })

  for (let i = 0; i < dirs.length; i++) {
      const dir = dirs[i]

      if (dir.isDirectory() && !(/^\d{2,3}-/.test(dir.name))) {
        console.log(`"src/modules/${dir.name}" does not follow modules standard. Please see https://github.com/wings-software/nextgenui/blob/master/src/modules/README.md`)
        process.exit(1)
      }
  }
})()
