/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

export enum PAGE_NAME {
  AccountResources = 'AccountResources',
  SmtpDetails = 'SmtpDetails',
  AuditTrailsPage = 'AuditTrailsPage',
  ServiceAccountsPage = 'ServiceAccountsPage',
  UsersPage = 'UsersPage',
  ServiceAccountDetails = 'ServiceAccountDetails',
  UserDetails = 'UserDetails',
  UserGroups = 'UserGroups',
  UserGroupDetails = 'UserGroupDetails',
  ResourceGroups = 'ResourceGroups',
  Roles = 'Roles',
  RoleDetails = 'RoleDetails',
  ResourceGroupDetails = 'ResourceGroupDetails',
  DelegateListing = 'DelegateListing',
  DelegateConfigurations = 'DelegateConfigurations',
  DelegateDetails = 'DelegateDetails',
  DelegateProfileDetails = 'DelegateProfileDetails',
  DelegateTokens = 'DelegateTokens',
  SecretsPage = 'SecretsPage',
  SecretDetails = 'SecretDetails',
  SecretReferences = 'SecretReferences',
  CreateSecretFromYamlPage = 'CreateSecretFromYamlPage',
  CITrialHomePage = 'CITrialHomePage',
  CIHomePage = 'CIHomePage',
  ConnectorsPage = 'ConnectorsPage',
  VariablesPage = 'VariablesPage',
  CreateConnectorFromYamlPage = 'CreateConnectorFromYamlPage',
  GitSyncRepoTab = 'GitSyncRepoTab',
  GitSyncEntityTab = 'GitSyncEntityTab',
  GitSyncErrors = 'GitSyncErrors',
  GitSyncConfigTab = 'GitSyncConfigTab',
  ConnectorDetailsPage = 'ConnectorDetailsPage',
  CIPipelineStudio = 'CIPipelineStudio',
  FullPageLogView = 'FullPageLogView',
  PipelinesPage = 'PipelinesPage',
  InputSetList = 'InputSetList',
  DeploymentsList = 'DeploymentsList',
  EnhancedInputSetForm = 'EnhancedInputSetForm',
  TriggersPage = 'TriggersPage',
  TriggersDetailPage = 'TriggersDetailPage',
  TriggersWizardPage = 'TriggersWizardPage',
  ExecutionPipelineView = 'ExecutionPipelineView',
  ExecutionPolicyEvaluationsView = 'ExecutionPolicyEvaluationsView',
  ExecutionSecurityView = 'ExecutionSecurityView',
  ExecutionInputsView = 'ExecutionInputsView',
  ExecutionArtifactsView = 'ExecutionArtifactsView',
  BuildTests = 'BuildTests',
  BuildCommits = 'BuildCommits',
  CIPipelineDeploymentList = 'CIPipelineDeploymentList',
  TemplatesPage = 'TemplatesPage',
  TemplateStudioWrapper = 'TemplateStudioWrapper',
  CDHomePage = 'CDHomePage',
  CDTrialHomePage = 'CDTrialHomePage',
  Services = 'Services',
  ServiceDetails = 'ServiceDetails',
  ServiceStudio = 'ServiceStudio',
  Environments = 'Environments',
  CDPipelineStudio = 'CDPipelineStudio',
  CDPipelineDeploymentList = 'CDPipelineDeploymentList',
  GitOpsPage = 'GitOpsPage',
  AccountConfiguration = 'AccountConfiguration',
  AccountOverview = 'AccountOverview',
  SubscriptionsPage = 'SubscriptionsPage',
  PlanPage = 'PlanPage',
  GetStartedWithCI = 'GetStartedWithCI',
  CFHomePage = 'CFHomePage',
  CFTrialHomePage = 'CFTrialHomePage',
  FeatureFlagsLandingPage = 'FeatureFlagsLandingPage',
  FeatureFlagsDetailPage = 'FeatureFlagsDetailPage',
  TargetGroupDetailPage = 'TargetGroupDetailPage',
  SegmentDetailPage = 'SegmentDetailPage',
  TargetsPage = 'TargetsPage',
  TargetDetailPage = 'TargetDetailPage',
  LegacyTargetDetailPage = 'LegacyTargetDetailPage',
  SegmentsPage = 'SegmentsPage',
  EnvironmentsPage = 'EnvironmentsPage',
  EnvironmentDetails = 'EnvironmentDetails',
  OnboardingPage = 'OnboardingPage',
  OnboardingDetailPage = 'OnboardingDetailPage',
  CFWorkflowsPage = 'CFWorkflowsPage',
  SecretDetailsHomePage = 'SecretDetailsHomePage',
  ChaosHomePage = 'ChaosHomePage'
}
