/*
 * Copyright 2021 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

export enum EXECUTION_STATUS_HARNESS_CD_NEXTGEN {
  NO_OP = 'NO_OP',
  RUNNING = 'RUNNING',
  INTERVENTION_WAITING = 'INTERVENTION_WAITING',
  TIMED_WAITING = 'TIMED_WAITING',
  ASYNC_WAITING = 'ASYNC_WAITING',
  TASK_WAITING = 'TASK_WAITING',
  DISCONTINUING = 'DISCONTINUING',
  PAUSING = 'PAUSING',
  QUEUED = 'QUEUED',
  SKIPPED = 'SKIPPED',
  PAUSED = 'PAUSED',
  ABORTED = 'ABORTED',
  ERRORED = 'ERRORED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  SUSPENDED = 'SUSPENDED',
  SUCCESS = 'SUCCESS',
  IGNORE_FAILED = 'IGNORE_FAILED',
  APPROVAL_WAITING = 'APPROVAL_WAITING',
  RESOURCE_WAITING = 'RESOURCE_WAITING',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  UNRECOGNIZED = 'UNRECOGNIZED'
}

export enum EXECUTION_STATUS_HARNESS_CD {
  ABORTED = 'ABORTED',
  DISCONTINUING = 'DISCONTINUING',
  ERROR = 'ERROR',
  FAILED = 'FAILED',
  NEW = 'NEW',
  PAUSED = 'PAUSED',
  PAUSING = 'PAUSING',
  QUEUED = 'QUEUED',
  RESUMED = 'RESUMED',
  RUNNING = 'RUNNING',
  SCHEDULED = 'SCHEDULED',
  STARTING = 'STARTING',
  SUCCESS = 'SUCCESS',
  WAITING = 'WAITING',
  SKIPPED = 'SKIPPED',
  ABORTING = 'ABORTING',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  PREPARING = 'PREPARING'
}
