query CCMMetaData {
  ccmMetaData {
    k8sClusterConnectorPresent
    cloudDataPresent
    awsConnectorsPresent
    gcpConnectorsPresent
    azureConnectorsPresent
    applicationDataPresent
    inventoryDataPresent
    clusterDataPresent
    isSampleClusterPresent
    defaultAzurePerspectiveId
    defaultAwsPerspectiveId
    defaultGcpPerspectiveId
    defaultClusterPerspectiveId
  }
}
