# Copyright 2021 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Shield 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.

query FetchBudgetSummary($id: String!) {
  budgetSummary(budgetId: $id) {
    id
    uuid: id
    name
    budgetAmount
    actualCost
    timeLeft
    timeUnit
    timeScope
    actualCostAlerts
    forecastCostAlerts
    forecastCost
    perspectiveId
    perspectiveName
    growthRate
    startTime
    type
    period
    alertThresholds {
      basedOn
      percentage
      emailAddresses
      slackWebhooks
      userGroupIds
    }
  }
}
