query FetchRecommendation($id: String!) {
  recommendationStats(id: $id) {
    totalMonthlyCost
    totalMonthlySaving
  }
  recommendationDetails(id: $id, resourceType: WORKLOAD) {
    ... on WorkloadRecommendationDTO {
      containerRecommendations
      items {
        containerName
        cpuHistogram {
          bucketWeights
          firstBucketSize
          growthRatio
          maxBucket
          minBucket
          numBuckets
          precomputed
          totalWeight
        }
        memoryHistogram {
          bucketWeights
          firstBucketSize
          growthRatio
          maxBucket
          minBucket
          numBuckets
          precomputed
          totalWeight
        }
      }
    }
  }
}
