query FetchPerspectiveDetailsSummary(
  $filters: [QLCEViewFilterWrapperInput]
  $aggregateFunction: [QLCEViewAggregationInput]
  $isClusterQuery: Boolean
) {
  perspectiveTrendStats(filters: $filters, aggregateFunction: $aggregateFunction, isClusterQuery: $isClusterQuery) {
    cost {
      statsDescription
      statsLabel
      statsTrend
      statsValue
      value
    }
  }

  perspectiveForecastCost(filters: $filters, aggregateFunction: $aggregateFunction, isClusterQuery: $isClusterQuery) {
    cost {
      statsLabel
      statsTrend
      statsValue
      statsDescription
    }
  }
}
