query FetchViewFields($filters: [QLCEViewFilterWrapperInput]) {
  perspectiveFields(filters: $filters) {
    fieldIdentifierData {
      identifier
      identifierName
      values {
        fieldId
        fieldName
        identifier
        identifierName
      }
    }
  }
}
