query Recommendations($filters: K8sRecommendationFilterDTOInput) {
  recommendationStatsV2(filter: $filters) {
    totalMonthlyCost
    totalMonthlySaving
  }

  recommendationsV2(filter: $filters) {
    items {
      id
      resourceType
      resourceName
      monthlyCost
      monthlySaving
    }
  }
}
