query FetchRecommendation($id: String!, $startTime: OffsetDateTime!, $endTime: OffsetDateTime!) {
  recommendationStats(id: $id) {
    totalMonthlyCost
    totalMonthlySaving
  }
  recommendationDetails(id: $id, resourceType: WORKLOAD, startTime: $startTime, endTime: $endTime) {
    ... on WorkloadRecommendationDTO {
      containerRecommendations
      items {
        containerRecommendation {
          numDays
          current {
            CPU
            MEMORY
          }
          lastDayCost {
            cpu
            memory
          }
        }
        containerName
        cpuHistogram {
          bucketWeights
          firstBucketSize
          growthRatio
          maxBucket
          minBucket
          numBuckets
          precomputed
          totalWeight
        }
        memoryHistogram {
          bucketWeights
          firstBucketSize
          growthRatio
          maxBucket
          minBucket
          numBuckets
          precomputed
          totalWeight
        }
      }
    }
  }
}
