query FetchBudgetsGridData($id: String!) {
  budgetCostData(budgetId: $id) {
    costData {
      time
      actualCost
      budgeted
      budgetVariance
      budgetVariancePercentage
      endTime
    }
    forecastCost
  }
  budgetSummary(budgetId: $id) {
    period
  }
}
