query FetchPerspectiveTotalCount(
  $filters: [QLCEViewFilterWrapperInput]
  $groupBy: [QLCEViewGroupByInput]
  $isClusterQuery: Boolean
) {
  perspectiveTotalCount(filters: $filters, groupBy: $groupBy, isClusterQuery: $isClusterQuery)
}
