query FetchWorkloadSummary($filters: [QLCEViewFilterWrapperInput]) {
  perspectiveTrendStats(
    filters: $filters
    aggregateFunction: [
      { operationType: SUM, columnName: "billingamount" }
      { operationType: SUM, columnName: "actualidlecost" }
      { operationType: SUM, columnName: "unallocatedcost" }
      { operationType: MAX, columnName: "startTime" }
      { operationType: MIN, columnName: "startTime" }
    ]
  ) {
    cost {
      statsLabel
      statsTrend
      statsValue
      statsDescription
    }
    idleCost {
      statsLabel
      statsTrend
      statsValue
      statsDescription
    }
    utilizedCost {
      statsLabel
      statsTrend
      statsValue
      statsDescription
    }
  }

  perspectiveGrid(
    filters: $filters
    aggregateFunction: [{ operationType: SUM, columnName: "cost" }]
    sortCriteria: []
    groupBy: { entityGroupBy: { fieldId: "workloadName", fieldName: "Workload Id", identifier: CLUSTER } }
    limit: 100
    offset: 0
  ) {
    data {
      clusterData {
        workloadName
        workloadType
        namespace
        clusterName
      }
    }
  }
}
