query FetchRecommendation(
  $id: String!
  $resourceType: ResourceType!
  $startTime: OffsetDateTime!
  $endTime: OffsetDateTime!
) {
  recommendationStatsV2(filter: { ids: [$id] }) {
    totalMonthlyCost
    totalMonthlySaving
  }
  recommendationsV2(filter: { ids: [$id], offset: 0, limit: 10 }) {
    items {
      clusterName
      namespace
      id
      resourceName
    }
  }
  recommendationDetails(id: $id, resourceType: $resourceType, startTime: $startTime, endTime: $endTime) {
    ... on WorkloadRecommendationDTO {
      containerRecommendations
      items {
        containerRecommendation {
          numDays
          current {
            CPU
            MEMORY
          }
          lastDayCost {
            cpu
            memory
          }
        }
        containerName
        cpuHistogram {
          bucketWeights
          firstBucketSize
          growthRatio
          maxBucket
          minBucket
          numBuckets
          precomputed
          totalWeight
        }
        memoryHistogram {
          bucketWeights
          firstBucketSize
          growthRatio
          maxBucket
          minBucket
          numBuckets
          precomputed
          totalWeight
        }
      }
    }

    ... on NodeRecommendationDTO {
      current {
        instanceCategory
        nodePools {
          sumNodes
          vm {
            avgPrice
            cpusPerVm
            memPerVm
            onDemandPrice
            type
          }
        }
        provider
        region
        service
      }
      id
      nodePoolId {
        clusterid
        nodepoolname
      }
      recommended {
        accuracy {
          cpu
          masterPrice
          memory
          nodes
          spotNodes
          spotPrice
          totalPrice
          workerPrice
        }
        instanceCategory
        nodePools {
          role
          sumNodes
          vmClass
          vm {
            avgPrice
            cpusPerVm
            memPerVm
            onDemandPrice
            type
          }
        }
        provider
        region
        service
      }
      resourceRequirement {
        allowBurst
        maxNodes
        minNodes
        onDemandPct
        sameSize
        sumCpu
        sumGpu
        sumMem
      }
    }
  }
}
