query Recommendations($filter: K8sRecommendationFilterDTOInput) {
  recommendationsV2(filter: $filter) {
    items {
      clusterName
      namespace
      id
      resourceType
      resourceName
      monthlyCost
      monthlySaving
    }
  }
}
