query Recommendations {
  recommendationStats {
    totalMonthlyCost
    totalMonthlySaving
  }

  recommendations {
    items {
      id
      resourceType
      resourceName
      monthlyCost
      monthlySaving
    }
  }
}
