query FetchBudgetSummary($id: String!) {
  budgetSummary(budgetId: $id) {
    id
    uuid: id
    name
    budgetAmount
    actualCost
    timeLeft
    timeUnit
    timeScope
    actualCostAlerts
    forecastCostAlerts
    forecastCost
    perspectiveId
    growthRate
    startTime
    type
    period
    alertThresholds {
      basedOn
      percentage
      emailAddresses
      userGroupIds
    }
  }
}
