query FetchBudget {
  budgetList {
    id
    uuid: id
    name
    budgetAmount
    actualCost
    timeLeft
    timeUnit
    timeScope
    actualCostAlerts
    forecastCostAlerts
    forecastCost
    perspectiveId
  }
}
