query FetchBudgetSummary($id: String!) {
  budgetSummary(budgetId: $id) {
    id
    name
    budgetAmount
    actualCost
    timeLeft
    timeUnit
    timeScope
    actualCostAlerts
    forecastCostAlerts
    forecastCost
  }
}
