/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly disabled: string
  readonly sectionHeader: string
  readonly subSectonHeader: string
  readonly stagesTreeBulletCircle: string
  readonly artifactHeader: string
  readonly mtop: string
  readonly customVariables: string
  readonly padSmall: string
  readonly inputWidth: string
  readonly nestedAccordions: string
  readonly nopadLeft: string
  readonly selectPopover: string
  readonly tabHeading: string
  readonly tabSubHeading: string
  readonly sectionCard: string
  readonly shadow: string
  readonly notwide: string
  readonly accordionTitle: string
  readonly cardSection: string
  readonly serviceDefinition: string
  readonly accordionSummary: string
  readonly header: string
  readonly subheading: string
  readonly inputheader: string
  readonly artifactInfoTooltip: string
  readonly manifestVariablesTable: string
  readonly skipVersioning: string
  readonly width50: string
  readonly width25: string
  readonly serviceSection: string
  readonly connectorMargin: string
  readonly layoutVerticalSpacing: string
  readonly verticalSpacingInput: string
  readonly listLabel: string
  readonly width400: string
}
export default styles
