rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - microfrontends/*
        - '!microfrontends/ChildAppMounter'
        - modules/72-templates-library/*
        - modules/72-triggers/*
        - modules/75-cd/*
        - modules/75-ce/*
        - modules/75-cf/*
        - modules/75-chaos/*
        - modules/75-ci/*
        - modules/85-cv/*
        - modules/85-sto-steps/*
        - modules/90-gitops/*
        - '@templates-library/*'
        - '@triggers/*'
        - '@cd/*'
        - '@ce/*'
        - '@cf/*'
        - '@chaos/*'
        - '@ci/*'
        - '@cv/*'
        - '@sto-steps/*'
        - '@gitops/*'
      paths:
        - lodash
        - name: js-yaml
          message: Please use methods from @common/utils/YamlHelperMethods instead of using js-yaml
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead of this
        - name: react-router
          message: import from "react-router-dom" instead
        - name: microfrontends
          message: Import from 'microfrontends' is only allowed in child apps
        - name: '@wings-software/uicore'
          importNames:
            - Color
            - FontVariation
            - Intent
            - Spacing
          message: import from "@harness/design-system" instead
        - name: yaml
          message: Please use methods from @common/utils/YamlHelperMethods instead of using yaml
  react/function-component-definition:
    - error
    - namedComponents: function-declaration
      unnamedComponents: arrow-function
overrides:
  - files:
      - '*.stories.tsx'
    rules:
      react/function-component-definition:
        - 'off'
