#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch" == "master" ]]; then
  echo "\033[0;31;1mYou can't commit directly to master branch\033[0m"
  exit 1
fi

if [[ "$branch" =~ ^release\/.* ]]; then
  echo "\033[0;31;1mYou cannot commit directly to release branch\033[0m"
    exit 1
fi


node ./scripts/lint-commit-message.js "$(cat "$1")"
