/* eslint-disable */
// this is an auto-generated file
declare const styles: {
  readonly main: string
  readonly graphWrapper: string
  readonly graph: string
  readonly stageWrapper: string
  readonly scrollLeft: string
  readonly scrollRight: string
  readonly stepCounts: string
  readonly stepCount: string
  readonly runningAnimation: string
  readonly errorMsg: string
  readonly stage: string
  readonly icon: string
  readonly success: string
  readonly running: string
  readonly failed: string
  readonly expired: string
  readonly aborted: string
  readonly suspended: string
  readonly approvalrejected: string
  readonly notstarted: string
  readonly waiting: string
  readonly approvalwaiting: string
  readonly interventionwaiting: string
  readonly queued: string
  readonly paused: string
  readonly pausing: string
  readonly skipped: string
  readonly parallelNodes: string
  readonly ghostNodes: string
  readonly moreStages: string
  readonly extraCount: string
  readonly pulse: string
  readonly infoPopover: string
  readonly title: string
  readonly section: string
  readonly sectionTitle: string
  readonly sectionData: string
}
export default styles
