rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - modules/30-auth-settings/*
        - modules/30-delegates/*
        - modules/30-secrets/*
        - modules/35-connectors/*
        - modules/35-user-profile/*
        - modules/40-gitsync/*
        - modules/45-dashboards/*
        - modules/45-projects-orgs/*
        - modules/70-pipeline/*
        - modules/72-templates-library/*
        - modules/75-cd/*
        - modules/75-ce/*
        - modules/75-cf/*
        - modules/75-ci/*
        - modules/85-cv/*
        - '@auth-settings/*'
        - '@delegates/*'
        - '@secrets/*'
        - '@connectors/*'
        - '@user-profile/*'
        - '@gitsync/*'
        - '@dashboards/*'
        - '@projects-orgs/*'
        - '@pipeline/*'
        - '@templates-library/*'
        - '@cd/*'
        - '@ce/*'
        - '@cf/*'
        - '@ci/*'
        - '@cv/*'
      paths:
        - lodash
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead
            of this
